package tech.medo.domain.runtimegovernance.detectruntimecapabilities

import org.springframework.stereotype.Component
import tech.medo.runtimegovernance.detectruntimecapabilities.DetectRuntimeCapabilitiesDecision

@Component
class DetectRuntimeCapabilitiesDecisionComponent : DetectRuntimeCapabilitiesDecision
