package tech.medo.domain.trainingorchestration.updatetrainingrunconfiguration

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.updatetrainingrunconfiguration.UpdateTrainingRunConfigurationDecision

@Component
class UpdateTrainingRunConfigurationDecisionComponent : UpdateTrainingRunConfigurationDecision
