package tech.medo.domain.runtimeagentoperations.revokedatasettrainingapproval

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.revokedatasettrainingapproval.RevokeDatasetTrainingApprovalDecision

@Component
class RevokeDatasetTrainingApprovalDecisionComponent : RevokeDatasetTrainingApprovalDecision
