package tech.medo.domain.federationmanagement.suspendparticipant

import org.springframework.stereotype.Component
import tech.medo.federationmanagement.suspendparticipant.SuspendParticipantDecision

@Component
class SuspendParticipantDecisionComponent : SuspendParticipantDecision
