package tech.medo.domain.trainingorchestration.starttraininground

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.starttraininground.StartTrainingRoundDecision

@Component
class StartTrainingRoundDecisionComponent : StartTrainingRoundDecision
