package tech.medo.domain.identityaccessmanagement.deactivateuseraccount

import org.springframework.stereotype.Component
import tech.medo.identityaccessmanagement.deactivateuseraccount.DeactivateUserAccountDecision

@Component
class DeactivateUserAccountDecisionComponent : DeactivateUserAccountDecision
