# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_client.proto\"4\n\x04\x44\x61ta\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x18\n\x05Reply\x12\x0f\n\x07succeed\x18\x01 \x01(\x08\x32&\n\x08Receiver\x12\x1a\n\x07receive\x12\x05.Data\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=21
  _globals['_DATA']._serialized_end=73
  _globals['_REPLY']._serialized_start=75
  _globals['_REPLY']._serialized_end=99
  _globals['_RECEIVER']._serialized_start=101
  _globals['_RECEIVER']._serialized_end=139
# @@protoc_insertion_point(module_scope)
