package tech.medo.domain.runtimeagentoperations.rejectexecutionplan

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.rejectexecutionplan.RejectExecutionPlanDecision

@Component
class RejectExecutionPlanDecisionComponent : RejectExecutionPlanDecision
