package tech.medo.domain.runtimeagentoperations.rejectdatasetfortraining

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.rejectdatasetfortraining.RejectDatasetForTrainingDecision

@Component
class RejectDatasetForTrainingDecisionComponent : RejectDatasetForTrainingDecision
