package tech.medo.domain.runtimeagentoperations.reprofileagentdataset

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.reprofileagentdataset.ReprofileAgentDatasetDecision

@Component
class ReprofileAgentDatasetDecisionComponent : ReprofileAgentDatasetDecision
