package tech.medo.domain.trainingorchestration.completetrainingjob

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.completetrainingjob.CompleteTrainingJobDecision

@Component
class CompleteTrainingJobDecisionComponent : CompleteTrainingJobDecision
