// Generated from config.json by the refine generator.
import { IResourceItem } from "@refinedev/core";
import { FlaskConical, LayoutDashboard, Package } from "lucide-react";

export const backendModules = [
  {
    name: "federation-learning-dictionary",
    label: "Federation Learning Dictionary",
    dataProviderName: "federation-learning-dictionary",
    apiUrl: import.meta.env.VITE_FEDERATION_LEARNING_DICTIONARY_API_URL ?? "http://localhost:8080",
    homeRoute: "/dictionary-catalog",
    resources: ["dictionary-catalog","dictionary-value-catalog"],
  },
  {
    name: "federation-learning-platform",
    label: "Federation Learning Platform",
    dataProviderName: "federation-learning-platform",
    apiUrl: import.meta.env.VITE_FEDERATION_LEARNING_PLATFORM_API_URL ?? "http://localhost:8081",
    homeRoute: "/audit-record-log",
    resources: ["audit-record-log","current-recommended-feature-schema-catalog","feature-schema-catalog","federation-membership-directory","federation-overview","model-artifact-catalog","model-version-catalog","organization-directory","runtime-capability-catalog","runtime-dataset-metadata-catalog","runtime-health-dashboard","runtime-identity-catalog","runtime-infrastructure-access-view","runtime-infrastructure-package-catalog","runtime-installation-guide","runtime-installation-plan-catalog","runtime-node-inventory-view","runtime-node-resource-latest","runtime-telemetry-latest","secure-aggregation-session-catalog","training-alert-catalog","training-job-dashboard","training-participant-eligibility","training-round-progress","training-run-configuration-catalog"],
  },
  {
    name: "federation-learning-runtime-agent",
    label: "Federation Learning Runtime Agent",
    dataProviderName: "federation-learning-runtime-agent",
    apiUrl: import.meta.env.VITE_FEDERATION_LEARNING_RUNTIME_AGENT_API_URL ?? "http://localhost:8082",
    homeRoute: "/agent-dataset-access-validation-catalog",
    resources: ["agent-dataset-access-validation-catalog","agent-runtime-infrastructure-connection-catalog","agent-runtime-node-inventory-catalog","agent-runtime-node-resource-latest","agent-runtime-telemetry-latest","dataset-capability","dataset-readiness","round-execution-catalog","runtime-agent-lifecycle-catalog","runtime-dataset-binding-catalog"],
  },
];

export const resources: IResourceItem[] = [
  {
    name: "dashboard",
    list: "/dashboard",
    meta: {
      label: "Dashboard",
      i18nKey: "resources.dashboard.label",
      icon: <LayoutDashboard />,
    },
  },
  {
    name: "datasetgovernance",
    meta: {
      label: "Dataset Governance",
      i18nKey: "chapters.datasetgovernance.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "dictionarymaintenance",
    meta: {
      label: "Dictionary Maintenance",
      i18nKey: "chapters.dictionarymaintenance.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "federationmanagement",
    meta: {
      label: "Federation Management",
      i18nKey: "chapters.federationmanagement.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "modellifecycle",
    meta: {
      label: "Model Lifecycle",
      i18nKey: "chapters.modellifecycle.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "modelrepository",
    meta: {
      label: "Model Repository",
      i18nKey: "chapters.modelrepository.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "organizationmanagement",
    meta: {
      label: "Organization Management",
      i18nKey: "chapters.organizationmanagement.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "runtimeagentoperations",
    meta: {
      label: "Runtime Agent Operations",
      i18nKey: "chapters.runtimeagentoperations.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "runtimegovernance",
    meta: {
      label: "Runtime Governance",
      i18nKey: "chapters.runtimegovernance.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "runtimemonitoring",
    meta: {
      label: "Runtime Monitoring",
      i18nKey: "chapters.runtimemonitoring.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "runtimeprovisioning",
    meta: {
      label: "Runtime Provisioning",
      i18nKey: "chapters.runtimeprovisioning.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "secureaggregation",
    meta: {
      label: "Secure Aggregation",
      i18nKey: "chapters.secureaggregation.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "trainingorchestration",
    meta: {
      label: "Training Orchestration",
      i18nKey: "chapters.trainingorchestration.label",
      icon: <FlaskConical />,
    },
  },
  {
    name: "agent_dataset_access_validation_catalog",
    list: "/agent-dataset-access-validation-catalog",
    show: "/agent-dataset-access-validation-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Dataset Access Validation Catalog",
      i18nKey: "resources.agent_dataset_access_validation_catalog.label",
      icon: <Package />,
      tableName: "agent_dataset_access_validation_catalog_read_model_entity",
      idField: "datasetAccessValidationId",
      idFields: ["datasetAccessValidationId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentdatasetaccessvalidation",
      queryRoute: "agentdatasetaccessvalidationcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_infrastructure_connection_catalog",
    list: "/agent-runtime-infrastructure-connection-catalog",
    show: "/agent-runtime-infrastructure-connection-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Infrastructure Connection Catalog",
      i18nKey: "resources.agent_runtime_infrastructure_connection_catalog.label",
      icon: <Package />,
      tableName: "agent_runtime_infrastructure_connection_catalog_read_model_entity",
      idField: "runtimeInfrastructureId",
      idFields: ["runtimeInfrastructureId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimeinfrastructureconnection",
      queryRoute: "agentruntimeinfrastructureconnectioncatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/agent-runtime-infrastructure-connection-catalog/:id/command/:command",
      commands: {
        recordRuntimeConnectionEstablished: { label: "Record Runtime Connection Established", i18nKey: "resources.agent_runtime_infrastructure_connection_catalog.commands.recordRuntimeConnectionEstablished.label", route: "/agent-runtime-infrastructure-connection-catalog/:id/command/record-runtime-connection-established", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_node_inventory_catalog",
    list: "/agent-runtime-node-inventory-catalog",
    show: "/agent-runtime-node-inventory-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Node Inventory Catalog",
      i18nKey: "resources.agent_runtime_node_inventory_catalog.label",
      icon: <Package />,
      tableName: "agent_runtime_node_inventory_catalog_read_model_entity",
      idField: "runtimeNodeInventoryReportId",
      idFields: ["runtimeNodeInventoryReportId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimenodeinventory",
      queryRoute: "agentruntimenodeinventorycatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_node_resource_latest",
    list: "/agent-runtime-node-resource-latest",
    show: "/agent-runtime-node-resource-latest/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Node Resource Latest",
      i18nKey: "resources.agent_runtime_node_resource_latest.label",
      icon: <Package />,
      tableName: "agent_runtime_node_resource_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimenoderesourcetelemetry",
      queryRoute: "agentruntimenoderesourcelatest",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_telemetry_latest",
    list: "/agent-runtime-telemetry-latest",
    show: "/agent-runtime-telemetry-latest/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Telemetry Latest",
      i18nKey: "resources.agent_runtime_telemetry_latest.label",
      icon: <Package />,
      tableName: "agent_runtime_telemetry_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimetelemetry",
      queryRoute: "agentruntimetelemetrylatest",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "audit_record_log",
    list: "/audit-record-log",
    show: "/audit-record-log/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Audit Record Log",
      i18nKey: "resources.audit_record_log.label",
      icon: <Package />,
      tableName: "audit_record_log_read_model_entity",
      idField: "auditRecordId",
      idFields: ["auditRecordId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "auditrecord",
      queryRoute: "auditrecordlog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "current_recommended_feature_schema_catalog",
    list: "/current-recommended-feature-schema-catalog",
    show: "/current-recommended-feature-schema-catalog/show/:id",
    meta: {
      parent: "datasetgovernance",
      label: "Current Recommended Feature Schema Catalog",
      i18nKey: "resources.current_recommended_feature_schema_catalog.label",
      icon: <Package />,
      tableName: "current_recommended_feature_schema_catalog_read_model_entity",
      idField: "featureDomain",
      idFields: ["featureDomain"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "featureschema",
      queryRoute: "currentrecommendedfeatureschemacatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "dataset_capability",
    list: "/dataset-capability",
    create: "/dataset-capability/command/declare-dataset",
    show: "/dataset-capability/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Dataset Capability",
      i18nKey: "resources.dataset_capability.label",
      icon: <Package />,
      tableName: "dataset_capability_read_model_entity",
      idField: "datasetId",
      idFields: ["datasetId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "dataset",
      queryRoute: "datasetcapability",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/dataset-capability/:id/command/:command",
      commands: {
        declareDataset: { label: "Declare Dataset", i18nKey: "resources.dataset_capability.commands.declareDataset.label", route: "/dataset-capability/command/declare-dataset", dataProviderName: "federation-learning-runtime-agent" },
        retryDatasetContractValidation: { label: "Retry Dataset Contract Validation", i18nKey: "resources.dataset_capability.commands.retryDatasetContractValidation.label", route: "/dataset-capability/:id/command/retry-dataset-contract-validation", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        rejectDatasetForTraining: { label: "Reject Dataset For Training", i18nKey: "resources.dataset_capability.commands.rejectDatasetForTraining.label", route: "/dataset-capability/:id/command/reject-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        approveDatasetForTraining: { label: "Approve Dataset For Training", i18nKey: "resources.dataset_capability.commands.approveDatasetForTraining.label", route: "/dataset-capability/:id/command/approve-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        revokeDatasetTrainingApproval: { label: "Revoke Dataset Training Approval", i18nKey: "resources.dataset_capability.commands.revokeDatasetTrainingApproval.label", route: "/dataset-capability/:id/command/revoke-dataset-training-approval", dataProviderName: "federation-learning-runtime-agent", stateField: "approvalStatus", allowedStates: ["Approved"] },
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.dataset_capability.commands.configureRuntimeDatasetBinding.label", route: "/dataset-capability/:id/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "dataset_readiness",
    list: "/dataset-readiness",
    create: "/dataset-readiness/command/declare-dataset",
    show: "/dataset-readiness/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Dataset Readiness",
      i18nKey: "resources.dataset_readiness.label",
      icon: <Package />,
      tableName: "dataset_readiness_read_model_entity",
      idField: "datasetId",
      idFields: ["datasetId"],
      actionControls: {"enabledFields":["canBeSelectedForTraining"]},
      aggregateRoute: "dataset",
      queryRoute: "datasetreadiness",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/dataset-readiness/:id/command/:command",
      commands: {
        declareDataset: { label: "Declare Dataset", i18nKey: "resources.dataset_readiness.commands.declareDataset.label", route: "/dataset-readiness/command/declare-dataset", dataProviderName: "federation-learning-runtime-agent" },
        retryDatasetContractValidation: { label: "Retry Dataset Contract Validation", i18nKey: "resources.dataset_readiness.commands.retryDatasetContractValidation.label", route: "/dataset-readiness/:id/command/retry-dataset-contract-validation", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        rejectDatasetForTraining: { label: "Reject Dataset For Training", i18nKey: "resources.dataset_readiness.commands.rejectDatasetForTraining.label", route: "/dataset-readiness/:id/command/reject-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        approveDatasetForTraining: { label: "Approve Dataset For Training", i18nKey: "resources.dataset_readiness.commands.approveDatasetForTraining.label", route: "/dataset-readiness/:id/command/approve-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        revokeDatasetTrainingApproval: { label: "Revoke Dataset Training Approval", i18nKey: "resources.dataset_readiness.commands.revokeDatasetTrainingApproval.label", route: "/dataset-readiness/:id/command/revoke-dataset-training-approval", dataProviderName: "federation-learning-runtime-agent", stateField: "approvalStatus", allowedStates: ["Approved"] },
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.dataset_readiness.commands.configureRuntimeDatasetBinding.label", route: "/dataset-readiness/:id/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "dictionary_catalog",
    list: "/dictionary-catalog",
    create: "/dictionary-catalog/command/register-dictionary",
    edit: "/dictionary-catalog/edit/:id",
    show: "/dictionary-catalog/show/:id",
    meta: {
      parent: "dictionarymaintenance",
      label: "Dictionary Catalog",
      i18nKey: "resources.dictionary_catalog.label",
      icon: <Package />,
      tableName: "dictionary_catalog_read_model_entity",
      idField: "dictionaryId",
      idFields: ["dictionaryId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "dictionary",
      queryRoute: "dictionarycatalog",
      dataProviderName: "federation-learning-dictionary",
      moduleName: "federation-learning-dictionary",
      moduleLabel: "Federation Learning Dictionary",
      commandRoute: "/dictionary-catalog/:id/command/:command",
      commands: {
        registerDictionary: { label: "Register Dictionary", i18nKey: "resources.dictionary_catalog.commands.registerDictionary.label", route: "/dictionary-catalog/command/register-dictionary", dataProviderName: "federation-learning-dictionary" },
        archiveDictionary: { label: "Archive Dictionary", i18nKey: "resources.dictionary_catalog.commands.archiveDictionary.label", route: "/dictionary-catalog/:id/command/archive-dictionary", dataProviderName: "federation-learning-dictionary", stateField: "state", allowedStates: ["Registered"] },
        addDictionaryValue: { label: "Add Dictionary Value", i18nKey: "resources.dictionary_catalog.commands.addDictionaryValue.label", route: "/dictionary-catalog/:id/command/add-dictionary-value", dataProviderName: "federation-learning-dictionary" },
      },
      canDelete: true,
    },
  },
  {
    name: "dictionary_value_catalog",
    list: "/dictionary-value-catalog",
    create: "/dictionary-value-catalog/command/add-dictionary-value",
    show: "/dictionary-value-catalog/show/:id",
    meta: {
      parent: "dictionarymaintenance",
      label: "Dictionary Value Catalog",
      i18nKey: "resources.dictionary_value_catalog.label",
      icon: <Package />,
      tableName: "dictionary_value_catalog_read_model_entity",
      idField: "dictionaryValueId",
      idFields: ["dictionaryValueId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "dictionaryvalue",
      queryRoute: "dictionaryvaluecatalog",
      dataProviderName: "federation-learning-dictionary",
      moduleName: "federation-learning-dictionary",
      moduleLabel: "Federation Learning Dictionary",
      commandRoute: "/dictionary-value-catalog/:id/command/:command",
      commands: {
        addDictionaryValue: { label: "Add Dictionary Value", i18nKey: "resources.dictionary_value_catalog.commands.addDictionaryValue.label", route: "/dictionary-value-catalog/command/add-dictionary-value", dataProviderName: "federation-learning-dictionary" },
        disableDictionaryValue: { label: "Disable Dictionary Value", i18nKey: "resources.dictionary_value_catalog.commands.disableDictionaryValue.label", route: "/dictionary-value-catalog/:id/command/disable-dictionary-value", dataProviderName: "federation-learning-dictionary", stateField: "state", allowedStates: ["Active"] },
        enableDictionaryValue: { label: "Enable Dictionary Value", i18nKey: "resources.dictionary_value_catalog.commands.enableDictionaryValue.label", route: "/dictionary-value-catalog/:id/command/enable-dictionary-value", dataProviderName: "federation-learning-dictionary", stateField: "state", allowedStates: ["Disabled"] },
      },
      canDelete: false,
    },
  },
  {
    name: "feature_schema_catalog",
    list: "/feature-schema-catalog",
    create: "/feature-schema-catalog/command/define-feature-schema",
    show: "/feature-schema-catalog/show/:id",
    meta: {
      parent: "datasetgovernance",
      label: "Feature Schema Catalog",
      i18nKey: "resources.feature_schema_catalog.label",
      icon: <Package />,
      tableName: "feature_schema_catalog_read_model_entity",
      idField: "featureSchemaId",
      idFields: ["featureSchemaId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "featureschema",
      queryRoute: "featureschemacatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/feature-schema-catalog/:id/command/:command",
      commands: {
        defineFeatureSchema: { label: "Define Feature Schema", i18nKey: "resources.feature_schema_catalog.commands.defineFeatureSchema.label", route: "/feature-schema-catalog/command/define-feature-schema", dataProviderName: "federation-learning-platform" },
        publishFeatureSchema: { label: "Publish Feature Schema", i18nKey: "resources.feature_schema_catalog.commands.publishFeatureSchema.label", route: "/feature-schema-catalog/:id/command/publish-feature-schema", dataProviderName: "federation-learning-platform", stateField: "schemaStatus", allowedStates: ["Draft"] },
        deprecateFeatureSchema: { label: "Deprecate Feature Schema", i18nKey: "resources.feature_schema_catalog.commands.deprecateFeatureSchema.label", route: "/feature-schema-catalog/:id/command/deprecate-feature-schema", dataProviderName: "federation-learning-platform", stateField: "schemaStatus", allowedStates: ["Published"] },
        retireFeatureSchema: { label: "Retire Feature Schema", i18nKey: "resources.feature_schema_catalog.commands.retireFeatureSchema.label", route: "/feature-schema-catalog/:id/command/retire-feature-schema", dataProviderName: "federation-learning-platform", stateField: "schemaStatus", allowedStates: ["Deprecated"] },
        supersedeFeatureSchemaVersion: { label: "Supersede Feature Schema Version", i18nKey: "resources.feature_schema_catalog.commands.supersedeFeatureSchemaVersion.label", route: "/feature-schema-catalog/:id/command/supersede-feature-schema-version", dataProviderName: "federation-learning-platform" },
        markCurrentRecommendedFeatureSchemaVersion: { label: "Mark Current Recommended Feature Schema Version", i18nKey: "resources.feature_schema_catalog.commands.markCurrentRecommendedFeatureSchemaVersion.label", route: "/feature-schema-catalog/:id/command/mark-current-recommended-feature-schema-version", dataProviderName: "federation-learning-platform" },
        declareDataset: { label: "Declare Dataset", i18nKey: "resources.feature_schema_catalog.commands.declareDataset.label", route: "/feature-schema-catalog/:id/command/declare-dataset", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "federation_membership_directory",
    list: "/federation-membership-directory",
    create: "/federation-membership-directory/command/invite-participant",
    show: "/federation-membership-directory/show/:id",
    meta: {
      parent: "federationmanagement",
      label: "Federation Membership Directory",
      i18nKey: "resources.federation_membership_directory.label",
      icon: <Package />,
      tableName: "federation_membership_directory_read_model_entity",
      idField: "federationId",
      idFields: ["federationId","organizationId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "federationmembership",
      queryRoute: "federationmembershipdirectory",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/federation-membership-directory/:id/command/:command",
      commands: {
        inviteParticipant: { label: "Invite Participant", i18nKey: "resources.federation_membership_directory.commands.inviteParticipant.label", route: "/federation-membership-directory/command/invite-participant", dataProviderName: "federation-learning-platform" },
        removeParticipant: { label: "Remove Participant", i18nKey: "resources.federation_membership_directory.commands.removeParticipant.label", route: "/federation-membership-directory/:id/command/remove-participant", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Suspended"] },
        approveParticipant: { label: "Approve Participant", i18nKey: "resources.federation_membership_directory.commands.approveParticipant.label", route: "/federation-membership-directory/:id/command/approve-participant", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Invited"] },
        rejectParticipant: { label: "Reject Participant", i18nKey: "resources.federation_membership_directory.commands.rejectParticipant.label", route: "/federation-membership-directory/:id/command/reject-participant", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Invited"] },
        revokeParticipantInvitation: { label: "Revoke Participant Invitation", i18nKey: "resources.federation_membership_directory.commands.revokeParticipantInvitation.label", route: "/federation-membership-directory/:id/command/revoke-participant-invitation", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Invited"] },
        suspendParticipant: { label: "Suspend Participant", i18nKey: "resources.federation_membership_directory.commands.suspendParticipant.label", route: "/federation-membership-directory/:id/command/suspend-participant", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Active"] },
        activateFederation: { label: "Activate Federation", i18nKey: "resources.federation_membership_directory.commands.activateFederation.label", route: "/federation-membership-directory/:id/command/activate-federation", dataProviderName: "federation-learning-platform", stateField: "membershipStatus", allowedStates: ["Draft"] },
      },
      canDelete: true,
    },
  },
  {
    name: "federation_overview",
    list: "/federation-overview",
    create: "/federation-overview/command/create-federation",
    show: "/federation-overview/show/:id",
    meta: {
      parent: "federationmanagement",
      label: "Federation Overview",
      i18nKey: "resources.federation_overview.label",
      icon: <Package />,
      tableName: "federation_overview_read_model_entity",
      idField: "federationId",
      idFields: ["federationId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "federation",
      queryRoute: "federationoverview",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/federation-overview/:id/command/:command",
      commands: {
        createFederation: { label: "Create Federation", i18nKey: "resources.federation_overview.commands.createFederation.label", route: "/federation-overview/command/create-federation", dataProviderName: "federation-learning-platform" },
        removeParticipant: { label: "Remove Participant", i18nKey: "resources.federation_overview.commands.removeParticipant.label", route: "/federation-overview/:id/command/remove-participant", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Suspended"] },
        activateFederation: { label: "Activate Federation", i18nKey: "resources.federation_overview.commands.activateFederation.label", route: "/federation-overview/:id/command/activate-federation", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Draft"] },
        suspendFederation: { label: "Suspend Federation", i18nKey: "resources.federation_overview.commands.suspendFederation.label", route: "/federation-overview/:id/command/suspend-federation", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Active"] },
        reactivateFederation: { label: "Reactivate Federation", i18nKey: "resources.federation_overview.commands.reactivateFederation.label", route: "/federation-overview/:id/command/reactivate-federation", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Suspended"] },
        inviteParticipant: { label: "Invite Participant", i18nKey: "resources.federation_overview.commands.inviteParticipant.label", route: "/federation-overview/:id/command/invite-participant", dataProviderName: "federation-learning-platform" },
        approveParticipant: { label: "Approve Participant", i18nKey: "resources.federation_overview.commands.approveParticipant.label", route: "/federation-overview/:id/command/approve-participant", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Invited"] },
        rejectParticipant: { label: "Reject Participant", i18nKey: "resources.federation_overview.commands.rejectParticipant.label", route: "/federation-overview/:id/command/reject-participant", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Invited"] },
        revokeParticipantInvitation: { label: "Revoke Participant Invitation", i18nKey: "resources.federation_overview.commands.revokeParticipantInvitation.label", route: "/federation-overview/:id/command/revoke-participant-invitation", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Invited"] },
        suspendParticipant: { label: "Suspend Participant", i18nKey: "resources.federation_overview.commands.suspendParticipant.label", route: "/federation-overview/:id/command/suspend-participant", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Active"] },
      },
      canDelete: true,
    },
  },
  {
    name: "model_artifact_catalog",
    list: "/model-artifact-catalog",
    create: "/model-artifact-catalog/command/register-model-artifact",
    show: "/model-artifact-catalog/show/:id",
    meta: {
      parent: "modelrepository",
      label: "Model Artifact Catalog",
      i18nKey: "resources.model_artifact_catalog.label",
      icon: <Package />,
      tableName: "model_artifact_catalog_read_model_entity",
      idField: "modelVersionId",
      idFields: ["modelVersionId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "modelartifact",
      queryRoute: "modelartifactcatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/model-artifact-catalog/:id/command/:command",
      commands: {
        registerModelArtifact: { label: "Register Model Artifact", i18nKey: "resources.model_artifact_catalog.commands.registerModelArtifact.label", route: "/model-artifact-catalog/command/register-model-artifact", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "model_version_catalog",
    list: "/model-version-catalog",
    show: "/model-version-catalog/show/:id",
    meta: {
      parent: "modellifecycle",
      label: "Model Version Catalog",
      i18nKey: "resources.model_version_catalog.label",
      icon: <Package />,
      tableName: "model_version_catalog_read_model_entity",
      idField: "modelVersionId",
      idFields: ["modelVersionId"],
      actionControls: {"blockedReasonField":"blockedReason","enabledFields":["canRecordEvaluationPackage","canApprove","canPromoteToProduction","canRollback","canRetire"]},
      aggregateRoute: "modelversion",
      queryRoute: "modelversioncatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/model-version-catalog/:id/command/:command",
      commands: {
        recordModelEvaluationPackage: { label: "Record Model Evaluation Package", i18nKey: "resources.model_version_catalog.commands.recordModelEvaluationPackage.label", route: "/model-version-catalog/:id/command/record-model-evaluation-package", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Candidate"] },
        approveModel: { label: "Approve Model", i18nKey: "resources.model_version_catalog.commands.approveModel.label", route: "/model-version-catalog/:id/command/approve-model", dataProviderName: "federation-learning-platform", enabledField: "canApprove", stateField: "state", allowedStates: ["EvaluationPackaged"] },
        promoteModelToProduction: { label: "Promote Model To Production", i18nKey: "resources.model_version_catalog.commands.promoteModelToProduction.label", route: "/model-version-catalog/:id/command/promote-model-to-production", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Approved"] },
        rollbackModelVersion: { label: "Rollback Model Version", i18nKey: "resources.model_version_catalog.commands.rollbackModelVersion.label", route: "/model-version-catalog/:id/command/rollback-model-version", dataProviderName: "federation-learning-platform", enabledField: "canRollback", stateField: "state", allowedStates: ["Production"] },
        retireModelVersion: { label: "Retire Model Version", i18nKey: "resources.model_version_catalog.commands.retireModelVersion.label", route: "/model-version-catalog/:id/command/retire-model-version", dataProviderName: "federation-learning-platform", enabledField: "canRetire", stateField: "state", allowedStates: ["Production"] },
      },
      canDelete: false,
    },
  },
  {
    name: "organization_directory",
    list: "/organization-directory",
    create: "/organization-directory/command/register-organization",
    show: "/organization-directory/show/:id",
    meta: {
      parent: "organizationmanagement",
      label: "Organization Directory",
      i18nKey: "resources.organization_directory.label",
      icon: <Package />,
      tableName: "organization_directory_read_model_entity",
      idField: "organizationId",
      idFields: ["organizationId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "organization",
      queryRoute: "organizationdirectory",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/organization-directory/:id/command/:command",
      commands: {
        registerOrganization: { label: "Register Organization", i18nKey: "resources.organization_directory.commands.registerOrganization.label", route: "/organization-directory/command/register-organization", dataProviderName: "federation-learning-platform" },
        activateOrganization: { label: "Activate Organization", i18nKey: "resources.organization_directory.commands.activateOrganization.label", route: "/organization-directory/:id/command/activate-organization", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Registered"] },
        deactivateOrganization: { label: "Deactivate Organization", i18nKey: "resources.organization_directory.commands.deactivateOrganization.label", route: "/organization-directory/:id/command/deactivate-organization", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Active"] },
        reactivateOrganization: { label: "Reactivate Organization", i18nKey: "resources.organization_directory.commands.reactivateOrganization.label", route: "/organization-directory/:id/command/reactivate-organization", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Deactivated"] },
        createRuntimeInstallationPlan: { label: "Create Runtime Installation Plan", i18nKey: "resources.organization_directory.commands.createRuntimeInstallationPlan.label", route: "/organization-directory/:id/command/create-runtime-installation-plan", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "round_execution_catalog",
    list: "/round-execution-catalog",
    show: "/round-execution-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Round Execution Catalog",
      i18nKey: "resources.round_execution_catalog.label",
      icon: <Package />,
      tableName: "round_execution_catalog_read_model_entity",
      idField: "roundExecutionId",
      idFields: ["roundExecutionId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "roundexecution",
      queryRoute: "roundexecutioncatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/round-execution-catalog/:id/command/:command",
      commands: {
        retryRoundExecutionAfterStartFailure: { label: "Retry Round Execution After Start Failure", i18nKey: "resources.round_execution_catalog.commands.retryRoundExecutionAfterStartFailure.label", route: "/round-execution-catalog/:id/command/retry-round-execution-after-start-failure", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["Running"] },
        completeRoundExecution: { label: "Complete Round Execution", i18nKey: "resources.round_execution_catalog.commands.completeRoundExecution.label", route: "/round-execution-catalog/:id/command/complete-round-execution", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["Running"] },
        failRoundExecution: { label: "Fail Round Execution", i18nKey: "resources.round_execution_catalog.commands.failRoundExecution.label", route: "/round-execution-catalog/:id/command/fail-round-execution", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["Running"] },
        retryRoundExecutionAfterRuntimeFailure: { label: "Retry Round Execution After Runtime Failure", i18nKey: "resources.round_execution_catalog.commands.retryRoundExecutionAfterRuntimeFailure.label", route: "/round-execution-catalog/:id/command/retry-round-execution-after-runtime-failure", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["Failed"] },
        submitModelUpdateSubmission: { label: "Submit Model Update Submission", i18nKey: "resources.round_execution_catalog.commands.submitModelUpdateSubmission.label", route: "/round-execution-catalog/:id/command/submit-model-update-submission", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_agent_lifecycle_catalog",
    list: "/runtime-agent-lifecycle-catalog",
    create: "/runtime-agent-lifecycle-catalog/command/load-runtime-agent-bootstrap-configuration",
    show: "/runtime-agent-lifecycle-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Runtime Agent Lifecycle Catalog",
      i18nKey: "resources.runtime_agent_lifecycle_catalog.label",
      icon: <Package />,
      tableName: "runtime_agent_lifecycle_catalog_read_model_entity",
      idField: "runtimeAgentId",
      idFields: ["runtimeAgentId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeagentlifecycle",
      queryRoute: "runtimeagentlifecyclecatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/runtime-agent-lifecycle-catalog/:id/command/:command",
      commands: {
        loadRuntimeAgentBootstrapConfiguration: { label: "Load Runtime Agent Bootstrap Configuration", i18nKey: "resources.runtime_agent_lifecycle_catalog.commands.loadRuntimeAgentBootstrapConfiguration.label", route: "/runtime-agent-lifecycle-catalog/command/load-runtime-agent-bootstrap-configuration", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_capability_catalog",
    list: "/runtime-capability-catalog",
    show: "/runtime-capability-catalog/show/:id",
    meta: {
      parent: "runtimegovernance",
      label: "Runtime Capability Catalog",
      i18nKey: "resources.runtime_capability_catalog.label",
      icon: <Package />,
      tableName: "runtime_capability_catalog_read_model_entity",
      idField: "runtimeId",
      idFields: ["runtimeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimecapability",
      queryRoute: "runtimecapabilitycatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "runtime_dataset_binding_catalog",
    list: "/runtime-dataset-binding-catalog",
    create: "/runtime-dataset-binding-catalog/command/configure-runtime-dataset-binding",
    show: "/runtime-dataset-binding-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Runtime Dataset Binding Catalog",
      i18nKey: "resources.runtime_dataset_binding_catalog.label",
      icon: <Package />,
      tableName: "runtime_dataset_binding_catalog_read_model_entity",
      idField: "runtimeDatasetBindingId",
      idFields: ["runtimeDatasetBindingId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimedatasetbinding",
      queryRoute: "runtimedatasetbindingcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/runtime-dataset-binding-catalog/:id/command/:command",
      commands: {
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.runtime_dataset_binding_catalog.commands.configureRuntimeDatasetBinding.label", route: "/runtime-dataset-binding-catalog/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_dataset_metadata_catalog",
    list: "/runtime-dataset-metadata-catalog",
    show: "/runtime-dataset-metadata-catalog/show/:id",
    meta: {
      parent: "datasetgovernance",
      label: "Runtime Dataset Metadata Catalog",
      i18nKey: "resources.runtime_dataset_metadata_catalog.label",
      icon: <Package />,
      tableName: "runtime_dataset_metadata_catalog_read_model_entity",
      idField: "metadataReportId",
      idFields: ["metadataReportId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimedatasetmetadata",
      queryRoute: "runtimedatasetmetadatacatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "runtime_health_dashboard",
    list: "/runtime-health-dashboard",
    show: "/runtime-health-dashboard/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Runtime Health Dashboard",
      i18nKey: "resources.runtime_health_dashboard.label",
      icon: <Package />,
      tableName: "runtime_health_dashboard_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "noderuntimehealth",
      queryRoute: "runtimehealthdashboard",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "runtime_identity_catalog",
    list: "/runtime-identity-catalog",
    show: "/runtime-identity-catalog/show/:id",
    meta: {
      parent: "runtimegovernance",
      label: "Runtime Identity Catalog",
      i18nKey: "resources.runtime_identity_catalog.label",
      icon: <Package />,
      tableName: "runtime_identity_catalog_read_model_entity",
      idField: "runtimeId",
      idFields: ["runtimeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeidentity",
      queryRoute: "runtimeidentitycatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/runtime-identity-catalog/:id/command/:command",
      commands: {
        revokeRuntimeIdentity: { label: "Revoke Runtime Identity", i18nKey: "resources.runtime_identity_catalog.commands.revokeRuntimeIdentity.label", route: "/runtime-identity-catalog/:id/command/revoke-runtime-identity", dataProviderName: "federation-learning-platform", stateField: "identityStatus", allowedStates: ["Active"] },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_infrastructure_access_view",
    list: "/runtime-infrastructure-access-view",
    show: "/runtime-infrastructure-access-view/show/:id",
    meta: {
      parent: "runtimeprovisioning",
      label: "Runtime Infrastructure Access View",
      i18nKey: "resources.runtime_infrastructure_access_view.label",
      icon: <Package />,
      tableName: "runtime_infrastructure_access_view_read_model_entity",
      idField: "runtimeInfrastructureId",
      idFields: ["runtimeInfrastructureId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeinfrastructure",
      queryRoute: "runtimeinfrastructureaccessview",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/runtime-infrastructure-access-view/:id/command/:command",
      commands: {
        registerRuntimeInfrastructure: { label: "Register Runtime Infrastructure", i18nKey: "resources.runtime_infrastructure_access_view.commands.registerRuntimeInfrastructure.label", route: "/runtime-infrastructure-access-view/:id/command/register-runtime-infrastructure", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Planned"] },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_infrastructure_package_catalog",
    list: "/runtime-infrastructure-package-catalog",
    create: "/runtime-infrastructure-package-catalog/command/register-runtime-infrastructure-package",
    show: "/runtime-infrastructure-package-catalog/show/:id",
    meta: {
      parent: "runtimeprovisioning",
      label: "Runtime Infrastructure Package Catalog",
      i18nKey: "resources.runtime_infrastructure_package_catalog.label",
      icon: <Package />,
      tableName: "runtime_infrastructure_package_catalog_read_model_entity",
      idField: "runtimeInfrastructurePackageId",
      idFields: ["runtimeInfrastructurePackageId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeinfrastructurepackage",
      queryRoute: "runtimeinfrastructurepackagecatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/runtime-infrastructure-package-catalog/:id/command/:command",
      commands: {
        registerRuntimeInfrastructurePackage: { label: "Register Runtime Infrastructure Package", i18nKey: "resources.runtime_infrastructure_package_catalog.commands.registerRuntimeInfrastructurePackage.label", route: "/runtime-infrastructure-package-catalog/command/register-runtime-infrastructure-package", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_installation_guide",
    list: "/runtime-installation-guide",
    create: "/runtime-installation-guide/command/create-runtime-installation-plan",
    show: "/runtime-installation-guide/show/:id",
    meta: {
      parent: "runtimeprovisioning",
      label: "Runtime Installation Guide",
      i18nKey: "resources.runtime_installation_guide.label",
      icon: <Package />,
      tableName: "runtime_installation_guide_read_model_entity",
      idField: "runtimeInstallationPlanId",
      idFields: ["runtimeInstallationPlanId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeinstallationplan",
      queryRoute: "runtimeinstallationguide",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/runtime-installation-guide/:id/command/:command",
      commands: {
        createRuntimeInstallationPlan: { label: "Create Runtime Installation Plan", i18nKey: "resources.runtime_installation_guide.commands.createRuntimeInstallationPlan.label", route: "/runtime-installation-guide/command/create-runtime-installation-plan", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_installation_plan_catalog",
    list: "/runtime-installation-plan-catalog",
    create: "/runtime-installation-plan-catalog/command/create-runtime-installation-plan",
    show: "/runtime-installation-plan-catalog/show/:id",
    meta: {
      parent: "runtimeprovisioning",
      label: "Runtime Installation Plan Catalog",
      i18nKey: "resources.runtime_installation_plan_catalog.label",
      icon: <Package />,
      tableName: "runtime_installation_plan_catalog_read_model_entity",
      idField: "runtimeInstallationPlanId",
      idFields: ["runtimeInstallationPlanId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeinstallationplan",
      queryRoute: "runtimeinstallationplancatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/runtime-installation-plan-catalog/:id/command/:command",
      commands: {
        createRuntimeInstallationPlan: { label: "Create Runtime Installation Plan", i18nKey: "resources.runtime_installation_plan_catalog.commands.createRuntimeInstallationPlan.label", route: "/runtime-installation-plan-catalog/command/create-runtime-installation-plan", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_node_inventory_view",
    list: "/runtime-node-inventory-view",
    show: "/runtime-node-inventory-view/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Runtime Node Inventory View",
      i18nKey: "resources.runtime_node_inventory_view.label",
      icon: <Package />,
      tableName: "runtime_node_inventory_view_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimenodeinventory",
      queryRoute: "runtimenodeinventoryview",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "runtime_node_resource_latest",
    list: "/runtime-node-resource-latest",
    show: "/runtime-node-resource-latest/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Runtime Node Resource Latest",
      i18nKey: "resources.runtime_node_resource_latest.label",
      icon: <Package />,
      tableName: "runtime_node_resource_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimenoderesourcetelemetry",
      queryRoute: "runtimenoderesourcelatest",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "runtime_telemetry_latest",
    list: "/runtime-telemetry-latest",
    show: "/runtime-telemetry-latest/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Runtime Telemetry Latest",
      i18nKey: "resources.runtime_telemetry_latest.label",
      icon: <Package />,
      tableName: "runtime_telemetry_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "noderuntimehealth",
      queryRoute: "runtimetelemetrylatest",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      canDelete: false,
    },
  },
  {
    name: "secure_aggregation_session_catalog",
    list: "/secure-aggregation-session-catalog",
    show: "/secure-aggregation-session-catalog/show/:id",
    meta: {
      parent: "secureaggregation",
      label: "Secure Aggregation Session Catalog",
      i18nKey: "resources.secure_aggregation_session_catalog.label",
      icon: <Package />,
      tableName: "secure_aggregation_session_catalog_read_model_entity",
      idField: "secureAggregationSessionId",
      idFields: ["secureAggregationSessionId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "secureaggregationsession",
      queryRoute: "secureaggregationsessioncatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/secure-aggregation-session-catalog/:id/command/:command",
      commands: {
        failSecureAggregationSession: { label: "Fail Secure Aggregation Session", i18nKey: "resources.secure_aggregation_session_catalog.commands.failSecureAggregationSession.label", route: "/secure-aggregation-session-catalog/:id/command/fail-secure-aggregation-session", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Planned"] },
        completeSecureAggregation: { label: "Complete Secure Aggregation", i18nKey: "resources.secure_aggregation_session_catalog.commands.completeSecureAggregation.label", route: "/secure-aggregation-session-catalog/:id/command/complete-secure-aggregation", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
  {
    name: "training_alert_catalog",
    list: "/training-alert-catalog",
    show: "/training-alert-catalog/show/:id",
    meta: {
      parent: "runtimemonitoring",
      label: "Training Alert Catalog",
      i18nKey: "resources.training_alert_catalog.label",
      icon: <Package />,
      tableName: "training_alert_catalog_read_model_entity",
      idField: "alertId",
      idFields: ["alertId"],
      actionControls: {"enabledFields":["canAcknowledge","canResolve"]},
      aggregateRoute: "trainingalert",
      queryRoute: "trainingalertcatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/training-alert-catalog/:id/command/:command",
      commands: {
        acknowledgeTrainingAlert: { label: "Acknowledge Training Alert", i18nKey: "resources.training_alert_catalog.commands.acknowledgeTrainingAlert.label", route: "/training-alert-catalog/:id/command/acknowledge-training-alert", dataProviderName: "federation-learning-platform", enabledField: "canAcknowledge", stateField: "state", allowedStates: ["Raised"] },
        resolveTrainingAlert: { label: "Resolve Training Alert", i18nKey: "resources.training_alert_catalog.commands.resolveTrainingAlert.label", route: "/training-alert-catalog/:id/command/resolve-training-alert", dataProviderName: "federation-learning-platform", enabledField: "canResolve", stateField: "state", allowedStates: ["Acknowledged"] },
      },
      canDelete: false,
    },
  },
  {
    name: "training_job_dashboard",
    list: "/training-job-dashboard",
    create: "/training-job-dashboard/command/create-training-job",
    show: "/training-job-dashboard/show/:id",
    meta: {
      parent: "trainingorchestration",
      label: "Training Job Dashboard",
      i18nKey: "resources.training_job_dashboard.label",
      icon: <Package />,
      tableName: "training_job_dashboard_read_model_entity",
      idField: "trainingJobId",
      idFields: ["trainingJobId"],
      actionControls: {"availableActionsField":"availableActions","blockedReasonField":"blockedReason","enabledFields":["canSubmit","canStartRound","canPause","canResume","canCancel","canComplete"]},
      aggregateRoute: "trainingjob",
      queryRoute: "trainingjobdashboard",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/training-job-dashboard/:id/command/:command",
      commands: {
        createTrainingJob: { label: "Create Training Job", i18nKey: "resources.training_job_dashboard.commands.createTrainingJob.label", route: "/training-job-dashboard/command/create-training-job", dataProviderName: "federation-learning-platform" },
        cancelTrainingJob: { label: "Cancel Training Job", i18nKey: "resources.training_job_dashboard.commands.cancelTrainingJob.label", route: "/training-job-dashboard/:id/command/cancel-training-job", dataProviderName: "federation-learning-platform", enabledField: "canCancel" },
        submitTrainingJob: { label: "Submit Training Job", i18nKey: "resources.training_job_dashboard.commands.submitTrainingJob.label", route: "/training-job-dashboard/:id/command/submit-training-job", dataProviderName: "federation-learning-platform", enabledField: "canSubmit", stateField: "state", allowedStates: ["Draft"] },
        pauseTrainingJob: { label: "Pause Training Job", i18nKey: "resources.training_job_dashboard.commands.pauseTrainingJob.label", route: "/training-job-dashboard/:id/command/pause-training-job", dataProviderName: "federation-learning-platform", enabledField: "canPause" },
        resumeTrainingJob: { label: "Resume Training Job", i18nKey: "resources.training_job_dashboard.commands.resumeTrainingJob.label", route: "/training-job-dashboard/:id/command/resume-training-job", dataProviderName: "federation-learning-platform", enabledField: "canResume", stateField: "state", allowedStates: ["Paused"] },
      },
      canDelete: true,
    },
  },
  {
    name: "training_participant_eligibility",
    list: "/training-participant-eligibility",
    create: "/training-participant-eligibility/command/create-training-job",
    show: "/training-participant-eligibility/show/:id",
    meta: {
      parent: "trainingorchestration",
      label: "Training Participant Eligibility",
      i18nKey: "resources.training_participant_eligibility.label",
      icon: <Package />,
      tableName: "training_participant_eligibility_read_model_entity",
      idField: "trainingJobId",
      idFields: ["trainingJobId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "trainingjob",
      queryRoute: "trainingparticipanteligibility",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/training-participant-eligibility/:id/command/:command",
      commands: {
        createTrainingJob: { label: "Create Training Job", i18nKey: "resources.training_participant_eligibility.commands.createTrainingJob.label", route: "/training-participant-eligibility/command/create-training-job", dataProviderName: "federation-learning-platform" },
        submitTrainingJob: { label: "Submit Training Job", i18nKey: "resources.training_participant_eligibility.commands.submitTrainingJob.label", route: "/training-participant-eligibility/:id/command/submit-training-job", dataProviderName: "federation-learning-platform", stateField: "participantStatus", allowedStates: ["Draft"] },
      },
      canDelete: false,
    },
  },
  {
    name: "training_round_progress",
    list: "/training-round-progress",
    show: "/training-round-progress/show/:id",
    meta: {
      parent: "trainingorchestration",
      label: "Training Round Progress",
      i18nKey: "resources.training_round_progress.label",
      icon: <Package />,
      tableName: "training_round_progress_read_model_entity",
      idField: "trainingJobId",
      idFields: ["trainingJobId","roundId"],
      actionControls: {"blockedReasonField":"blockedReason","enabledFields":[]},
      aggregateRoute: "traininground",
      queryRoute: "trainingroundprogress",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/training-round-progress/:id/command/:command",
      commands: {
        cancelTrainingJob: { label: "Cancel Training Job", i18nKey: "resources.training_round_progress.commands.cancelTrainingJob.label", route: "/training-round-progress/:id/command/cancel-training-job", dataProviderName: "federation-learning-platform" },
        retryRoundExecutionAfterStartFailure: { label: "Retry Round Execution After Start Failure", i18nKey: "resources.training_round_progress.commands.retryRoundExecutionAfterStartFailure.label", route: "/training-round-progress/:id/command/retry-round-execution-after-start-failure", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Running"] },
        completeRoundExecution: { label: "Complete Round Execution", i18nKey: "resources.training_round_progress.commands.completeRoundExecution.label", route: "/training-round-progress/:id/command/complete-round-execution", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Running"] },
        failRoundExecution: { label: "Fail Round Execution", i18nKey: "resources.training_round_progress.commands.failRoundExecution.label", route: "/training-round-progress/:id/command/fail-round-execution", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Running"] },
        retryRoundExecutionAfterRuntimeFailure: { label: "Retry Round Execution After Runtime Failure", i18nKey: "resources.training_round_progress.commands.retryRoundExecutionAfterRuntimeFailure.label", route: "/training-round-progress/:id/command/retry-round-execution-after-runtime-failure", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Failed"] },
        submitGlobalModelEvaluation: { label: "Submit Global Model Evaluation", i18nKey: "resources.training_round_progress.commands.submitGlobalModelEvaluation.label", route: "/training-round-progress/:id/command/submit-global-model-evaluation", dataProviderName: "federation-learning-platform" },
        submitTrainingJob: { label: "Submit Training Job", i18nKey: "resources.training_round_progress.commands.submitTrainingJob.label", route: "/training-round-progress/:id/command/submit-training-job", dataProviderName: "federation-learning-platform", stateField: "state", allowedStates: ["Draft"] },
        pauseTrainingJob: { label: "Pause Training Job", i18nKey: "resources.training_round_progress.commands.pauseTrainingJob.label", route: "/training-round-progress/:id/command/pause-training-job", dataProviderName: "federation-learning-platform" },
      },
      canDelete: true,
    },
  },
  {
    name: "training_run_configuration_catalog",
    list: "/training-run-configuration-catalog",
    create: "/training-run-configuration-catalog/command/define-training-run-configuration",
    edit: "/training-run-configuration-catalog/edit/:id",
    show: "/training-run-configuration-catalog/show/:id",
    meta: {
      parent: "trainingorchestration",
      label: "Training Run Configuration Catalog",
      i18nKey: "resources.training_run_configuration_catalog.label",
      icon: <Package />,
      tableName: "training_run_configuration_catalog_read_model_entity",
      idField: "trainingRunConfigurationId",
      idFields: ["trainingRunConfigurationId"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "trainingrunconfiguration",
      queryRoute: "trainingrunconfigurationcatalog",
      dataProviderName: "federation-learning-platform",
      moduleName: "federation-learning-platform",
      moduleLabel: "Federation Learning Platform",
      commandRoute: "/training-run-configuration-catalog/:id/command/:command",
      commands: {
        defineTrainingRunConfiguration: { label: "Define Training Run Configuration", i18nKey: "resources.training_run_configuration_catalog.commands.defineTrainingRunConfiguration.label", route: "/training-run-configuration-catalog/command/define-training-run-configuration", dataProviderName: "federation-learning-platform" },
        createTrainingJob: { label: "Create Training Job", i18nKey: "resources.training_run_configuration_catalog.commands.createTrainingJob.label", route: "/training-run-configuration-catalog/:id/command/create-training-job", dataProviderName: "federation-learning-platform" },
      },
      canDelete: false,
    },
  },
];
