package tech.medo.domain.secureaggregation.createsecureaggregationsession

import org.springframework.stereotype.Component
import tech.medo.secureaggregation.createsecureaggregationsession.CreateSecureAggregationSessionDecision

@Component
class CreateSecureAggregationSessionDecisionComponent : CreateSecureAggregationSessionDecision
