services:
  federation-learning-runtime-engine:
    build:
      context: .
      dockerfile: ./docker/pytorch/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-python:3.11-slim}
        PLUGIN_PROFILE: ${RUNTIME_ENGINE_PLUGIN_PROFILE:-full}
    image: ${RUNTIME_ENGINE_IMAGE:-medol/federation-learning-runtime-engine:0.0.1-SNAPSHOT}
