package tech.medo.domain.trainingorchestration.resumetrainingjob

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.resumetrainingjob.ResumeTrainingJobDecision

@Component
class ResumeTrainingJobDecisionComponent : ResumeTrainingJobDecision
