package tech.medo.domain.runtimeagentoperations.reportagentruntimetelemetry

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.reportagentruntimetelemetry.ReportAgentRuntimeTelemetryDecision

@Component
class ReportAgentRuntimeTelemetryDecisionComponent : ReportAgentRuntimeTelemetryDecision
