resources:
  - "../../base"
  - "configmap.yaml"
namespace: "federation-learning-platform"
labels:
  - pairs:
      "app.kubernetes.io/part-of": "federation-learning-platform"
      "medol.dev/environment": "dev"
    includeSelectors: true
    includeTemplates: true
patches:
  - path: "patches/console-envfrom.yaml"
  - path: "patches/federation-learning-support-envfrom.yaml"
  - path: "patches/federation-learning-platform-envfrom.yaml"
  - path: "patches/federation-learning-runtime-agent-envfrom.yaml"
