apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-secret"
  labels:
    "app.kubernetes.io/name": "postgres-secret"
    "app.kubernetes.io/component": "application-secret"
    "app.kubernetes.io/managed-by": "medol-operations-generator"
type: "Opaque"
stringData:
  username: "medol"
  password: "change-me"
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "federation-learning-support-dev-secret"
  labels:
    "app.kubernetes.io/name": "federation-learning-support-dev-secret"
    "app.kubernetes.io/component": "application-secret"
    "app.kubernetes.io/managed-by": "medol-operations-generator"
type: "Opaque"
stringData:
  DB_PASSWORD: "change-me"
  DB_USERNAME: "medol"
  MEDOL_SECURITY_ADMIN_BOOTSTRAP_SETUP_TOKEN: "change-me"
  MEDOL_SECURITY_INTERNAL_TOKEN: "local-dev-internal-token"
  MEDOL_SECURITY_JWT_SECRET: "change-me-change-me-change-me-change-me"
  UMADB_API_KEY: ""
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "federation-learning-platform-dev-secret"
  labels:
    "app.kubernetes.io/name": "federation-learning-platform-dev-secret"
    "app.kubernetes.io/component": "application-secret"
    "app.kubernetes.io/managed-by": "medol-operations-generator"
type: "Opaque"
stringData:
  DB_PASSWORD: "change-me"
  DB_USERNAME: "medol"
  MEDOL_SECURITY_INTERNAL_TOKEN: "local-dev-internal-token"
  MEDOL_SECURITY_JWT_SECRET: "change-me-change-me-change-me-change-me"
  RUNTIME_AGENT_ORGANIZATION_ID: "replace-with-participant-organization-id"
  UMADB_API_KEY: ""
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "federation-learning-runtime-agent-dev-secret"
  labels:
    "app.kubernetes.io/name": "federation-learning-runtime-agent-dev-secret"
    "app.kubernetes.io/component": "application-secret"
    "app.kubernetes.io/managed-by": "medol-operations-generator"
type: "Opaque"
stringData:
  DB_PASSWORD: "change-me"
  DB_USERNAME: "medol"
  MEDOL_SECURITY_INTERNAL_TOKEN: "local-dev-internal-token"
  MEDOL_SECURITY_JWT_SECRET: "change-me-change-me-change-me-change-me"
  UMADB_API_KEY: ""
