package tech.medo.domain.runtimeagentoperations.revalidateagentdatasetaccess

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.revalidateagentdatasetaccess.RevalidateAgentDatasetAccessDecision

@Component
class RevalidateAgentDatasetAccessDecisionComponent : RevalidateAgentDatasetAccessDecision
