package tech.medo.iam.infrastructure.security

import java.nio.charset.StandardCharsets
import java.util.UUID
import java.util.concurrent.CompletableFuture
import org.axonframework.messaging.core.Metadata
import org.axonframework.messaging.commandhandling.gateway.CommandGateway
import org.springframework.stereotype.Component
import tech.medo.identityaccessmanagement.grantpermissiontorole.GrantPermissionToRoleCommand
import tech.medo.identityaccessmanagement.registerpermission.RegisterPermissionCommand
import tech.medo.identityaccessmanagement.registerrole.RegisterRoleCommand

@Component
class IamAuthorizationBootstrap(
    private val commandGateway: CommandGateway,
) {
    fun initialize(metadata: Metadata): CompletableFuture<Unit> {
        val commands = buildList {
            permissions.forEach { permission ->
                add(
                    RegisterPermissionCommand(
                        permissionId = permissionIdFor(permission.code),
                        permissionCode = permission.code,
                        permissionName = permission.name,
                        description = permission.description,
                    ),
                )
            }
            roles.forEach { role ->
                add(
                    RegisterRoleCommand(
                        roleId = roleIdFor(role.code),
                        roleCode = role.code,
                        roleName = role.name,
                    ),
                )
            }
            grants.forEach { grant ->
                add(
                    GrantPermissionToRoleCommand(
                        roleId = roleIdFor(grant.roleCode),
                        roleCode = grant.roleCode,
                        permissionCodes = listOf(grant.permissionCode),
                    ),
                )
            }
        }

        return commands.fold(CompletableFuture.completedFuture(Unit)) { future, command ->
            future.thenCompose {
                commandGateway.send(command, metadata).resultMessage.thenApply { Unit }
            }
        }
    }

    private data class SeedPermission(
        val code: String,
        val name: String,
        val description: String?,
    )

    private data class SeedRole(
        val code: String,
        val name: String,
    )

    private data class SeedGrant(
        val roleCode: String,
        val permissionCode: String,
    )

    private fun roleIdFor(roleCode: String): UUID =
        UUID.nameUUIDFromBytes("iam-role:${roleCode.lowercase()}".toByteArray(StandardCharsets.UTF_8))

    private fun permissionIdFor(permissionCode: String): UUID =
        UUID.nameUUIDFromBytes("iam-permission:${permissionCode.lowercase()}".toByteArray(StandardCharsets.UTF_8))

    companion object {
        private val permissions = listOf(
            SeedPermission("*:*", "All permissions", "All permissions"),
            SeedPermission("acknowledge_training_alert:execute", "acknowledge_training_alert:execute", "acknowledge_training_alert:execute"),
            SeedPermission("activate_federation:execute", "activate_federation:execute", "activate_federation:execute"),
            SeedPermission("activate_organization:execute", "activate_organization:execute", "activate_organization:execute"),
            SeedPermission("activate_runtime_identity:execute", "activate_runtime_identity:execute", "activate_runtime_identity:execute"),
            SeedPermission("add_dictionary_value:execute", "add_dictionary_value:execute", "add_dictionary_value:execute"),
            SeedPermission("agent_dataset_access_validation_catalog:list", "agent_dataset_access_validation_catalog:list", "agent_dataset_access_validation_catalog:list"),
            SeedPermission("agent_dataset_access_validation_catalog:read", "agent_dataset_access_validation_catalog:read", "agent_dataset_access_validation_catalog:read"),
            SeedPermission("agent_runtime_infrastructure_connection_catalog:list", "agent_runtime_infrastructure_connection_catalog:list", "agent_runtime_infrastructure_connection_catalog:list"),
            SeedPermission("agent_runtime_infrastructure_connection_catalog:read", "agent_runtime_infrastructure_connection_catalog:read", "agent_runtime_infrastructure_connection_catalog:read"),
            SeedPermission("agent_runtime_node_inventory_catalog:list", "agent_runtime_node_inventory_catalog:list", "agent_runtime_node_inventory_catalog:list"),
            SeedPermission("agent_runtime_node_inventory_catalog:read", "agent_runtime_node_inventory_catalog:read", "agent_runtime_node_inventory_catalog:read"),
            SeedPermission("agent_runtime_node_resource_latest:list", "agent_runtime_node_resource_latest:list", "agent_runtime_node_resource_latest:list"),
            SeedPermission("agent_runtime_node_resource_latest:read", "agent_runtime_node_resource_latest:read", "agent_runtime_node_resource_latest:read"),
            SeedPermission("agent_runtime_telemetry_latest:list", "agent_runtime_telemetry_latest:list", "agent_runtime_telemetry_latest:list"),
            SeedPermission("agent_runtime_telemetry_latest:read", "agent_runtime_telemetry_latest:read", "agent_runtime_telemetry_latest:read"),
            SeedPermission("approve_dataset_for_training:execute", "approve_dataset_for_training:execute", "approve_dataset_for_training:execute"),
            SeedPermission("approve_model:execute", "approve_model:execute", "approve_model:execute"),
            SeedPermission("approve_participant:execute", "approve_participant:execute", "approve_participant:execute"),
            SeedPermission("archive_dictionary:execute", "archive_dictionary:execute", "archive_dictionary:execute"),
            SeedPermission("assign_role_to_user:execute", "assign_role_to_user:execute", "assign_role_to_user:execute"),
            SeedPermission("audit_record_log:list", "audit_record_log:list", "audit_record_log:list"),
            SeedPermission("audit_record_log:read", "audit_record_log:read", "audit_record_log:read"),
            SeedPermission("bind_user_account_to_organization:execute", "bind_user_account_to_organization:execute", "bind_user_account_to_organization:execute"),
            SeedPermission("cancel_training_job:execute", "cancel_training_job:execute", "cancel_training_job:execute"),
            SeedPermission("complete_homomorphic_aggregation_session:execute", "complete_homomorphic_aggregation_session:execute", "complete_homomorphic_aggregation_session:execute"),
            SeedPermission("configure_runtime_dataset_binding:execute", "configure_runtime_dataset_binding:execute", "configure_runtime_dataset_binding:execute"),
            SeedPermission("confirm_runtime_infrastructure_prepared:execute", "confirm_runtime_infrastructure_prepared:execute", "confirm_runtime_infrastructure_prepared:execute"),
            SeedPermission("create_federation:execute", "create_federation:execute", "create_federation:execute"),
            SeedPermission("create_runtime_installation_plan:execute", "create_runtime_installation_plan:execute", "create_runtime_installation_plan:execute"),
            SeedPermission("create_training_job:execute", "create_training_job:execute", "create_training_job:execute"),
            SeedPermission("current_recommended_feature_schema_catalog:list", "current_recommended_feature_schema_catalog:list", "current_recommended_feature_schema_catalog:list"),
            SeedPermission("current_recommended_feature_schema_catalog:read", "current_recommended_feature_schema_catalog:read", "current_recommended_feature_schema_catalog:read"),
            SeedPermission("dataset_capability:list", "dataset_capability:list", "dataset_capability:list"),
            SeedPermission("dataset_capability:read", "dataset_capability:read", "dataset_capability:read"),
            SeedPermission("dataset_readiness:list", "dataset_readiness:list", "dataset_readiness:list"),
            SeedPermission("dataset_readiness:read", "dataset_readiness:read", "dataset_readiness:read"),
            SeedPermission("deactivate_organization:execute", "deactivate_organization:execute", "deactivate_organization:execute"),
            SeedPermission("deactivate_user_account:execute", "deactivate_user_account:execute", "deactivate_user_account:execute"),
            SeedPermission("declare_dataset:execute", "declare_dataset:execute", "declare_dataset:execute"),
            SeedPermission("define_feature_schema:execute", "define_feature_schema:execute", "define_feature_schema:execute"),
            SeedPermission("define_training_run_configuration:execute", "define_training_run_configuration:execute", "define_training_run_configuration:execute"),
            SeedPermission("deploy_runtime_agent:execute", "deploy_runtime_agent:execute", "deploy_runtime_agent:execute"),
            SeedPermission("deprecate_feature_schema:execute", "deprecate_feature_schema:execute", "deprecate_feature_schema:execute"),
            SeedPermission("detect_runtime_capabilities:execute", "detect_runtime_capabilities:execute", "detect_runtime_capabilities:execute"),
            SeedPermission("dictionary_catalog:list", "dictionary_catalog:list", "dictionary_catalog:list"),
            SeedPermission("dictionary_catalog:read", "dictionary_catalog:read", "dictionary_catalog:read"),
            SeedPermission("dictionary_value_catalog:list", "dictionary_value_catalog:list", "dictionary_value_catalog:list"),
            SeedPermission("dictionary_value_catalog:read", "dictionary_value_catalog:read", "dictionary_value_catalog:read"),
            SeedPermission("disable_dictionary_value:execute", "disable_dictionary_value:execute", "disable_dictionary_value:execute"),
            SeedPermission("discard_file:execute", "discard_file:execute", "discard_file:execute"),
            SeedPermission("download_file:execute", "download_file:execute", "download_file:execute"),
            SeedPermission("download_model_artifact:execute", "download_model_artifact:execute", "download_model_artifact:execute"),
            SeedPermission("enable_dictionary_value:execute", "enable_dictionary_value:execute", "enable_dictionary_value:execute"),
            SeedPermission("fail_secure_aggregation_session:execute", "fail_secure_aggregation_session:execute", "fail_secure_aggregation_session:execute"),
            SeedPermission("fail_training_round:execute", "fail_training_round:execute", "fail_training_round:execute"),
            SeedPermission("feature_schema_catalog:list", "feature_schema_catalog:list", "feature_schema_catalog:list"),
            SeedPermission("feature_schema_catalog:read", "feature_schema_catalog:read", "feature_schema_catalog:read"),
            SeedPermission("federation_membership_directory:list", "federation_membership_directory:list", "federation_membership_directory:list"),
            SeedPermission("federation_membership_directory:read", "federation_membership_directory:read", "federation_membership_directory:read"),
            SeedPermission("federation_overview:list", "federation_overview:list", "federation_overview:list"),
            SeedPermission("federation_overview:read", "federation_overview:read", "federation_overview:read"),
            SeedPermission("generate_user_account_login_password:execute", "generate_user_account_login_password:execute", "generate_user_account_login_password:execute"),
            SeedPermission("grant_permission_to_role:execute", "grant_permission_to_role:execute", "grant_permission_to_role:execute"),
            SeedPermission("invite_participant:execute", "invite_participant:execute", "invite_participant:execute"),
            SeedPermission("issue_service_account_api_token:execute", "issue_service_account_api_token:execute", "issue_service_account_api_token:execute"),
            SeedPermission("load_runtime_agent_bootstrap_configuration:execute", "load_runtime_agent_bootstrap_configuration:execute", "load_runtime_agent_bootstrap_configuration:execute"),
            SeedPermission("mark_current_recommended_feature_schema_version:execute", "mark_current_recommended_feature_schema_version:execute", "mark_current_recommended_feature_schema_version:execute"),
            SeedPermission("mark_file_referenced:execute", "mark_file_referenced:execute", "mark_file_referenced:execute"),
            SeedPermission("model_artifact_catalog:list", "model_artifact_catalog:list", "model_artifact_catalog:list"),
            SeedPermission("model_artifact_catalog:read", "model_artifact_catalog:read", "model_artifact_catalog:read"),
            SeedPermission("model_catalog:list", "model_catalog:list", "model_catalog:list"),
            SeedPermission("model_catalog:read", "model_catalog:read", "model_catalog:read"),
            SeedPermission("organization_directory:list", "organization_directory:list", "organization_directory:list"),
            SeedPermission("organization_directory:read", "organization_directory:read", "organization_directory:read"),
            SeedPermission("pause_training_job:execute", "pause_training_job:execute", "pause_training_job:execute"),
            SeedPermission("permission_catalog:list", "permission_catalog:list", "permission_catalog:list"),
            SeedPermission("permission_catalog:read", "permission_catalog:read", "permission_catalog:read"),
            SeedPermission("plan_runtime_infrastructure:execute", "plan_runtime_infrastructure:execute", "plan_runtime_infrastructure:execute"),
            SeedPermission("prepare_homomorphic_encryption_context:execute", "prepare_homomorphic_encryption_context:execute", "prepare_homomorphic_encryption_context:execute"),
            SeedPermission("profile_agent_dataset:execute", "profile_agent_dataset:execute", "profile_agent_dataset:execute"),
            SeedPermission("promote_model_to_production:execute", "promote_model_to_production:execute", "promote_model_to_production:execute"),
            SeedPermission("publish_feature_schema:execute", "publish_feature_schema:execute", "publish_feature_schema:execute"),
            SeedPermission("reactivate_federation:execute", "reactivate_federation:execute", "reactivate_federation:execute"),
            SeedPermission("reactivate_organization:execute", "reactivate_organization:execute", "reactivate_organization:execute"),
            SeedPermission("record_encrypted_model_update:execute", "record_encrypted_model_update:execute", "record_encrypted_model_update:execute"),
            SeedPermission("record_model_evaluation_package:execute", "record_model_evaluation_package:execute", "record_model_evaluation_package:execute"),
            SeedPermission("register_dictionary:execute", "register_dictionary:execute", "register_dictionary:execute"),
            SeedPermission("register_model_artifact:execute", "register_model_artifact:execute", "register_model_artifact:execute"),
            SeedPermission("register_organization:execute", "register_organization:execute", "register_organization:execute"),
            SeedPermission("register_permission:execute", "register_permission:execute", "register_permission:execute"),
            SeedPermission("register_role:execute", "register_role:execute", "register_role:execute"),
            SeedPermission("register_runtime_infrastructure_package:execute", "register_runtime_infrastructure_package:execute", "register_runtime_infrastructure_package:execute"),
            SeedPermission("register_runtime_infrastructure:execute", "register_runtime_infrastructure:execute", "register_runtime_infrastructure:execute"),
            SeedPermission("register_user_account:execute", "register_user_account:execute", "register_user_account:execute"),
            SeedPermission("reject_dataset_for_training:execute", "reject_dataset_for_training:execute", "reject_dataset_for_training:execute"),
            SeedPermission("reject_participant:execute", "reject_participant:execute", "reject_participant:execute"),
            SeedPermission("remove_participant:execute", "remove_participant:execute", "remove_participant:execute"),
            SeedPermission("report_runtime_agent_started:execute", "report_runtime_agent_started:execute", "report_runtime_agent_started:execute"),
            SeedPermission("report_runtime_instance_self_check_passed:execute", "report_runtime_instance_self_check_passed:execute", "report_runtime_instance_self_check_passed:execute"),
            SeedPermission("reprofile_agent_dataset:execute", "reprofile_agent_dataset:execute", "reprofile_agent_dataset:execute"),
            SeedPermission("resolve_training_alert:execute", "resolve_training_alert:execute", "resolve_training_alert:execute"),
            SeedPermission("resume_training_job:execute", "resume_training_job:execute", "resume_training_job:execute"),
            SeedPermission("retire_feature_schema:execute", "retire_feature_schema:execute", "retire_feature_schema:execute"),
            SeedPermission("retire_model:execute", "retire_model:execute", "retire_model:execute"),
            SeedPermission("retry_dataset_contract_validation:execute", "retry_dataset_contract_validation:execute", "retry_dataset_contract_validation:execute"),
            SeedPermission("retry_round_execution_after_runtime_failure:execute", "retry_round_execution_after_runtime_failure:execute", "retry_round_execution_after_runtime_failure:execute"),
            SeedPermission("retry_round_execution_after_start_failure:execute", "retry_round_execution_after_start_failure:execute", "retry_round_execution_after_start_failure:execute"),
            SeedPermission("retry_runtime_agent_deployment:execute", "retry_runtime_agent_deployment:execute", "retry_runtime_agent_deployment:execute"),
            SeedPermission("retry_runtime_infrastructure_verification:execute", "retry_runtime_infrastructure_verification:execute", "retry_runtime_infrastructure_verification:execute"),
            SeedPermission("retry_training_round_participant_selection:execute", "retry_training_round_participant_selection:execute", "retry_training_round_participant_selection:execute"),
            SeedPermission("revalidate_agent_dataset_access:execute", "revalidate_agent_dataset_access:execute", "revalidate_agent_dataset_access:execute"),
            SeedPermission("revoke_dataset_training_approval:execute", "revoke_dataset_training_approval:execute", "revoke_dataset_training_approval:execute"),
            SeedPermission("revoke_participant_invitation:execute", "revoke_participant_invitation:execute", "revoke_participant_invitation:execute"),
            SeedPermission("revoke_runtime_identity:execute", "revoke_runtime_identity:execute", "revoke_runtime_identity:execute"),
            SeedPermission("role_catalog:list", "role_catalog:list", "role_catalog:list"),
            SeedPermission("role_catalog:read", "role_catalog:read", "role_catalog:read"),
            SeedPermission("role_permission_grant_catalog:list", "role_permission_grant_catalog:list", "role_permission_grant_catalog:list"),
            SeedPermission("role_permission_grant_catalog:read", "role_permission_grant_catalog:read", "role_permission_grant_catalog:read"),
            SeedPermission("rollback_model:execute", "rollback_model:execute", "rollback_model:execute"),
            SeedPermission("round_execution_catalog:list", "round_execution_catalog:list", "round_execution_catalog:list"),
            SeedPermission("round_execution_catalog:read", "round_execution_catalog:read", "round_execution_catalog:read"),
            SeedPermission("runtime_agent_endpoint_catalog:list", "runtime_agent_endpoint_catalog:list", "runtime_agent_endpoint_catalog:list"),
            SeedPermission("runtime_agent_endpoint_catalog:read", "runtime_agent_endpoint_catalog:read", "runtime_agent_endpoint_catalog:read"),
            SeedPermission("runtime_agent_lifecycle_catalog:list", "runtime_agent_lifecycle_catalog:list", "runtime_agent_lifecycle_catalog:list"),
            SeedPermission("runtime_agent_lifecycle_catalog:read", "runtime_agent_lifecycle_catalog:read", "runtime_agent_lifecycle_catalog:read"),
            SeedPermission("runtime_capability_catalog:list", "runtime_capability_catalog:list", "runtime_capability_catalog:list"),
            SeedPermission("runtime_capability_catalog:read", "runtime_capability_catalog:read", "runtime_capability_catalog:read"),
            SeedPermission("runtime_dataset_binding_catalog:list", "runtime_dataset_binding_catalog:list", "runtime_dataset_binding_catalog:list"),
            SeedPermission("runtime_dataset_binding_catalog:read", "runtime_dataset_binding_catalog:read", "runtime_dataset_binding_catalog:read"),
            SeedPermission("runtime_dataset_metadata_catalog:list", "runtime_dataset_metadata_catalog:list", "runtime_dataset_metadata_catalog:list"),
            SeedPermission("runtime_dataset_metadata_catalog:read", "runtime_dataset_metadata_catalog:read", "runtime_dataset_metadata_catalog:read"),
            SeedPermission("runtime_health_dashboard:list", "runtime_health_dashboard:list", "runtime_health_dashboard:list"),
            SeedPermission("runtime_health_dashboard:read", "runtime_health_dashboard:read", "runtime_health_dashboard:read"),
            SeedPermission("runtime_identity_catalog:list", "runtime_identity_catalog:list", "runtime_identity_catalog:list"),
            SeedPermission("runtime_identity_catalog:read", "runtime_identity_catalog:read", "runtime_identity_catalog:read"),
            SeedPermission("runtime_infrastructure_access_view:list", "runtime_infrastructure_access_view:list", "runtime_infrastructure_access_view:list"),
            SeedPermission("runtime_infrastructure_access_view:read", "runtime_infrastructure_access_view:read", "runtime_infrastructure_access_view:read"),
            SeedPermission("runtime_infrastructure_package_catalog:list", "runtime_infrastructure_package_catalog:list", "runtime_infrastructure_package_catalog:list"),
            SeedPermission("runtime_infrastructure_package_catalog:read", "runtime_infrastructure_package_catalog:read", "runtime_infrastructure_package_catalog:read"),
            SeedPermission("runtime_installation_guide:list", "runtime_installation_guide:list", "runtime_installation_guide:list"),
            SeedPermission("runtime_installation_guide:read", "runtime_installation_guide:read", "runtime_installation_guide:read"),
            SeedPermission("runtime_installation_plan_catalog:list", "runtime_installation_plan_catalog:list", "runtime_installation_plan_catalog:list"),
            SeedPermission("runtime_installation_plan_catalog:read", "runtime_installation_plan_catalog:read", "runtime_installation_plan_catalog:read"),
            SeedPermission("runtime_node_inventory_view:list", "runtime_node_inventory_view:list", "runtime_node_inventory_view:list"),
            SeedPermission("runtime_node_inventory_view:read", "runtime_node_inventory_view:read", "runtime_node_inventory_view:read"),
            SeedPermission("runtime_node_resource_latest:list", "runtime_node_resource_latest:list", "runtime_node_resource_latest:list"),
            SeedPermission("runtime_node_resource_latest:read", "runtime_node_resource_latest:read", "runtime_node_resource_latest:read"),
            SeedPermission("runtime_telemetry_latest:list", "runtime_telemetry_latest:list", "runtime_telemetry_latest:list"),
            SeedPermission("runtime_telemetry_latest:read", "runtime_telemetry_latest:read", "runtime_telemetry_latest:read"),
            SeedPermission("secure_aggregation_session_catalog:list", "secure_aggregation_session_catalog:list", "secure_aggregation_session_catalog:list"),
            SeedPermission("secure_aggregation_session_catalog:read", "secure_aggregation_session_catalog:read", "secure_aggregation_session_catalog:read"),
            SeedPermission("service_account_api_token_catalog:list", "service_account_api_token_catalog:list", "service_account_api_token_catalog:list"),
            SeedPermission("service_account_api_token_catalog:read", "service_account_api_token_catalog:read", "service_account_api_token_catalog:read"),
            SeedPermission("submit_model_update_submission:execute", "submit_model_update_submission:execute", "submit_model_update_submission:execute"),
            SeedPermission("submit_training_job:execute", "submit_training_job:execute", "submit_training_job:execute"),
            SeedPermission("supersede_feature_schema_version:execute", "supersede_feature_schema_version:execute", "supersede_feature_schema_version:execute"),
            SeedPermission("suspend_federation:execute", "suspend_federation:execute", "suspend_federation:execute"),
            SeedPermission("suspend_participant:execute", "suspend_participant:execute", "suspend_participant:execute"),
            SeedPermission("training_alert_catalog:list", "training_alert_catalog:list", "training_alert_catalog:list"),
            SeedPermission("training_alert_catalog:read", "training_alert_catalog:read", "training_alert_catalog:read"),
            SeedPermission("training_job_dashboard:list", "training_job_dashboard:list", "training_job_dashboard:list"),
            SeedPermission("training_job_dashboard:read", "training_job_dashboard:read", "training_job_dashboard:read"),
            SeedPermission("training_participant_eligibility:list", "training_participant_eligibility:list", "training_participant_eligibility:list"),
            SeedPermission("training_participant_eligibility:read", "training_participant_eligibility:read", "training_participant_eligibility:read"),
            SeedPermission("training_round_progress:list", "training_round_progress:list", "training_round_progress:list"),
            SeedPermission("training_round_progress:read", "training_round_progress:read", "training_round_progress:read"),
            SeedPermission("training_run_configuration_catalog:list", "training_run_configuration_catalog:list", "training_run_configuration_catalog:list"),
            SeedPermission("training_run_configuration_catalog:read", "training_run_configuration_catalog:read", "training_run_configuration_catalog:read"),
            SeedPermission("update_dictionary:execute", "update_dictionary:execute", "update_dictionary:execute"),
            SeedPermission("update_training_run_configuration:execute", "update_training_run_configuration:execute", "update_training_run_configuration:execute"),
            SeedPermission("upload_file:execute", "upload_file:execute", "upload_file:execute"),
            SeedPermission("uploaded_file_catalog:list", "uploaded_file_catalog:list", "uploaded_file_catalog:list"),
            SeedPermission("uploaded_file_catalog:read", "uploaded_file_catalog:read", "uploaded_file_catalog:read"),
            SeedPermission("user_account_catalog:list", "user_account_catalog:list", "user_account_catalog:list"),
            SeedPermission("user_account_catalog:read", "user_account_catalog:read", "user_account_catalog:read"),
            SeedPermission("user_organization_membership_directory:list", "user_organization_membership_directory:list", "user_organization_membership_directory:list"),
            SeedPermission("user_organization_membership_directory:read", "user_organization_membership_directory:read", "user_organization_membership_directory:read"),
            SeedPermission("user_role_assignment_catalog:list", "user_role_assignment_catalog:list", "user_role_assignment_catalog:list"),
            SeedPermission("user_role_assignment_catalog:read", "user_role_assignment_catalog:read", "user_role_assignment_catalog:read"),
            SeedPermission("validate_agent_dataset_access:execute", "validate_agent_dataset_access:execute", "validate_agent_dataset_access:execute"),
            SeedPermission("verify_runtime_infrastructure:execute", "verify_runtime_infrastructure:execute", "verify_runtime_infrastructure:execute")
        )

        private val roles = listOf(
            SeedRole("ADMIN", "Administrator"),
            SeedRole("ACTOR_AGGREGATION_RUNTIME", "Aggregation Runtime"),
            SeedRole("ACTOR_COMPLIANCE_OFFICER", "Compliance Officer"),
            SeedRole("ACTOR_DATA_OWNER", "Data Owner"),
            SeedRole("ACTOR_DATA_STEWARD", "Data Steward"),
            SeedRole("ACTOR_FEDERATION_OWNER", "Federation Owner"),
            SeedRole("ACTOR_GOVERNANCE_REVIEWER", "Governance Reviewer"),
            SeedRole("ACTOR_IDENTITY_ADMINISTRATOR", "Identity Administrator"),
            SeedRole("ACTOR_MLOPS_ENGINEER", "MLOps Engineer"),
            SeedRole("ACTOR_NODE_OPERATOR", "Node Operator"),
            SeedRole("ACTOR_ORGANIZATION_ADMIN", "Organization Admin"),
            SeedRole("ACTOR_PLATFORM_ADMIN", "Platform Admin"),
            SeedRole("ACTOR_PLATFORM_SERVICE", "Platform Service"),
            SeedRole("ACTOR_PLATFORM_USER", "Platform User"),
            SeedRole("ACTOR_RELEASE_MANAGER", "Release Manager"),
            SeedRole("ACTOR_RESEARCH_LEAD", "Research Lead"),
            SeedRole("ACTOR_RUNTIME_AGENT", "Runtime Agent"),
            SeedRole("ACTOR_RUNTIME_INSTALLER", "Runtime Installer"),
            SeedRole("ACTOR_SECURE_AGGREGATION_SERVICE", "Secure Aggregation Service"),
            SeedRole("ACTOR_SECURITY_REVIEWER", "Security Reviewer"),
            SeedRole("ACTOR_SUPER_ADMINISTRATOR", "Super Administrator"),
            SeedRole("ACTOR_TRAINING_OPERATOR", "Training Operator"),
            SeedRole("SERVICE_ACCOUNT", "Service Account")
        )

        private val grants = listOf(
            SeedGrant("ADMIN", "*:*"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "fail_training_round:execute"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_job_dashboard:list"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_job_dashboard:read"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_participant_eligibility:list"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_participant_eligibility:read"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_round_progress:list"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_round_progress:read"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_run_configuration_catalog:list"),
            SeedGrant("ACTOR_AGGREGATION_RUNTIME", "training_run_configuration_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_dataset_access_validation_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_dataset_access_validation_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_infrastructure_connection_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_infrastructure_connection_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_node_inventory_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_node_inventory_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_node_resource_latest:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_node_resource_latest:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_telemetry_latest:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "agent_runtime_telemetry_latest:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "approve_dataset_for_training:execute"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "dataset_capability:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "dataset_capability:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "dataset_readiness:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "dataset_readiness:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "reject_dataset_for_training:execute"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "revoke_dataset_training_approval:execute"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "round_execution_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "round_execution_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "runtime_agent_lifecycle_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "runtime_agent_lifecycle_catalog:read"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "runtime_dataset_binding_catalog:list"),
            SeedGrant("ACTOR_COMPLIANCE_OFFICER", "runtime_dataset_binding_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_dataset_access_validation_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_dataset_access_validation_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_infrastructure_connection_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_infrastructure_connection_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_node_inventory_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_node_inventory_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_node_resource_latest:list"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_node_resource_latest:read"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_telemetry_latest:list"),
            SeedGrant("ACTOR_DATA_OWNER", "agent_runtime_telemetry_latest:read"),
            SeedGrant("ACTOR_DATA_OWNER", "dataset_capability:list"),
            SeedGrant("ACTOR_DATA_OWNER", "dataset_capability:read"),
            SeedGrant("ACTOR_DATA_OWNER", "dataset_readiness:list"),
            SeedGrant("ACTOR_DATA_OWNER", "dataset_readiness:read"),
            SeedGrant("ACTOR_DATA_OWNER", "declare_dataset:execute"),
            SeedGrant("ACTOR_DATA_OWNER", "retry_dataset_contract_validation:execute"),
            SeedGrant("ACTOR_DATA_OWNER", "round_execution_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "round_execution_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "runtime_agent_lifecycle_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "runtime_agent_lifecycle_catalog:read"),
            SeedGrant("ACTOR_DATA_OWNER", "runtime_dataset_binding_catalog:list"),
            SeedGrant("ACTOR_DATA_OWNER", "runtime_dataset_binding_catalog:read"),
            SeedGrant("ACTOR_DATA_STEWARD", "current_recommended_feature_schema_catalog:list"),
            SeedGrant("ACTOR_DATA_STEWARD", "current_recommended_feature_schema_catalog:read"),
            SeedGrant("ACTOR_DATA_STEWARD", "define_feature_schema:execute"),
            SeedGrant("ACTOR_DATA_STEWARD", "deprecate_feature_schema:execute"),
            SeedGrant("ACTOR_DATA_STEWARD", "feature_schema_catalog:list"),
            SeedGrant("ACTOR_DATA_STEWARD", "feature_schema_catalog:read"),
            SeedGrant("ACTOR_DATA_STEWARD", "mark_current_recommended_feature_schema_version:execute"),
            SeedGrant("ACTOR_DATA_STEWARD", "publish_feature_schema:execute"),
            SeedGrant("ACTOR_DATA_STEWARD", "retire_feature_schema:execute"),
            SeedGrant("ACTOR_DATA_STEWARD", "runtime_dataset_metadata_catalog:list"),
            SeedGrant("ACTOR_DATA_STEWARD", "runtime_dataset_metadata_catalog:read"),
            SeedGrant("ACTOR_DATA_STEWARD", "supersede_feature_schema_version:execute"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "federation_membership_directory:list"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "federation_membership_directory:read"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "federation_overview:list"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "federation_overview:read"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "invite_participant:execute"),
            SeedGrant("ACTOR_FEDERATION_OWNER", "revoke_participant_invitation:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "approve_model:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "approve_participant:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "federation_membership_directory:list"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "federation_membership_directory:read"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "federation_overview:list"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "federation_overview:read"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "model_catalog:list"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "model_catalog:read"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "record_model_evaluation_package:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "reject_participant:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "remove_participant:execute"),
            SeedGrant("ACTOR_GOVERNANCE_REVIEWER", "suspend_participant:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "assign_role_to_user:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "deactivate_user_account:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "generate_user_account_login_password:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "grant_permission_to_role:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "permission_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "permission_catalog:read"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "register_permission:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "register_role:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "register_user_account:execute"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "role_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "role_catalog:read"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "role_permission_grant_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "role_permission_grant_catalog:read"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "service_account_api_token_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "service_account_api_token_catalog:read"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "user_account_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "user_account_catalog:read"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "user_role_assignment_catalog:list"),
            SeedGrant("ACTOR_IDENTITY_ADMINISTRATOR", "user_role_assignment_catalog:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "acknowledge_training_alert:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "audit_record_log:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "audit_record_log:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "cancel_training_job:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "define_training_run_configuration:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "download_model_artifact:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "model_artifact_catalog:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "model_artifact_catalog:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "pause_training_job:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "register_model_artifact:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "resolve_training_alert:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "resume_training_job:execute"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_health_dashboard:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_health_dashboard:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_node_inventory_view:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_node_inventory_view:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_node_resource_latest:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_node_resource_latest:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_telemetry_latest:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "runtime_telemetry_latest:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_alert_catalog:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_alert_catalog:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_job_dashboard:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_job_dashboard:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_participant_eligibility:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_participant_eligibility:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_round_progress:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_round_progress:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_run_configuration_catalog:list"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "training_run_configuration_catalog:read"),
            SeedGrant("ACTOR_MLOPS_ENGINEER", "update_training_run_configuration:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_dataset_access_validation_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_dataset_access_validation_catalog:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_infrastructure_connection_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_infrastructure_connection_catalog:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_node_inventory_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_node_inventory_catalog:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_node_resource_latest:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_node_resource_latest:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_telemetry_latest:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "agent_runtime_telemetry_latest:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "configure_runtime_dataset_binding:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "dataset_capability:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "dataset_capability:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "dataset_readiness:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "dataset_readiness:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "reprofile_agent_dataset:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "retry_round_execution_after_runtime_failure:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "retry_round_execution_after_start_failure:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "revalidate_agent_dataset_access:execute"),
            SeedGrant("ACTOR_NODE_OPERATOR", "round_execution_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "round_execution_catalog:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "runtime_agent_lifecycle_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "runtime_agent_lifecycle_catalog:read"),
            SeedGrant("ACTOR_NODE_OPERATOR", "runtime_dataset_binding_catalog:list"),
            SeedGrant("ACTOR_NODE_OPERATOR", "runtime_dataset_binding_catalog:read"),
            SeedGrant("ACTOR_ORGANIZATION_ADMIN", "organization_directory:list"),
            SeedGrant("ACTOR_ORGANIZATION_ADMIN", "organization_directory:read"),
            SeedGrant("ACTOR_ORGANIZATION_ADMIN", "register_organization:execute"),
            SeedGrant("ACTOR_ORGANIZATION_ADMIN", "user_organization_membership_directory:list"),
            SeedGrant("ACTOR_ORGANIZATION_ADMIN", "user_organization_membership_directory:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "activate_federation:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "activate_organization:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "activate_runtime_identity:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "add_dictionary_value:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "archive_dictionary:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "bind_user_account_to_organization:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "create_federation:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "create_runtime_installation_plan:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "deactivate_organization:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "deploy_runtime_agent:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "dictionary_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "dictionary_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "dictionary_value_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "dictionary_value_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "disable_dictionary_value:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "enable_dictionary_value:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "federation_membership_directory:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "federation_membership_directory:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "federation_overview:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "federation_overview:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "organization_directory:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "organization_directory:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "plan_runtime_infrastructure:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "reactivate_federation:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "reactivate_organization:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "register_dictionary:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "register_runtime_infrastructure_package:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "retry_runtime_agent_deployment:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "retry_runtime_infrastructure_verification:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_agent_endpoint_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_agent_endpoint_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_capability_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_capability_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_identity_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_identity_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_infrastructure_access_view:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_infrastructure_access_view:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_infrastructure_package_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_infrastructure_package_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_installation_guide:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_installation_guide:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_installation_plan_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "runtime_installation_plan_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "suspend_federation:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "update_dictionary:execute"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "user_organization_membership_directory:list"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "user_organization_membership_directory:read"),
            SeedGrant("ACTOR_PLATFORM_ADMIN", "verify_runtime_infrastructure:execute"),
            SeedGrant("ACTOR_PLATFORM_SERVICE", "mark_file_referenced:execute"),
            SeedGrant("ACTOR_PLATFORM_SERVICE", "uploaded_file_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_SERVICE", "uploaded_file_catalog:read"),
            SeedGrant("ACTOR_PLATFORM_USER", "discard_file:execute"),
            SeedGrant("ACTOR_PLATFORM_USER", "download_file:execute"),
            SeedGrant("ACTOR_PLATFORM_USER", "upload_file:execute"),
            SeedGrant("ACTOR_PLATFORM_USER", "uploaded_file_catalog:list"),
            SeedGrant("ACTOR_PLATFORM_USER", "uploaded_file_catalog:read"),
            SeedGrant("ACTOR_RELEASE_MANAGER", "model_catalog:list"),
            SeedGrant("ACTOR_RELEASE_MANAGER", "model_catalog:read"),
            SeedGrant("ACTOR_RELEASE_MANAGER", "promote_model_to_production:execute"),
            SeedGrant("ACTOR_RELEASE_MANAGER", "retire_model:execute"),
            SeedGrant("ACTOR_RELEASE_MANAGER", "rollback_model:execute"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "create_training_job:execute"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "submit_training_job:execute"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_job_dashboard:list"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_job_dashboard:read"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_participant_eligibility:list"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_participant_eligibility:read"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_round_progress:list"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_round_progress:read"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_run_configuration_catalog:list"),
            SeedGrant("ACTOR_RESEARCH_LEAD", "training_run_configuration_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_dataset_access_validation_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_dataset_access_validation_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_infrastructure_connection_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_infrastructure_connection_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_node_inventory_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_node_inventory_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_node_resource_latest:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_node_resource_latest:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_telemetry_latest:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "agent_runtime_telemetry_latest:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "dataset_capability:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "dataset_capability:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "dataset_readiness:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "dataset_readiness:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "detect_runtime_capabilities:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "load_runtime_agent_bootstrap_configuration:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "profile_agent_dataset:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "report_runtime_agent_started:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "report_runtime_instance_self_check_passed:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "round_execution_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "round_execution_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_agent_lifecycle_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_agent_lifecycle_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_capability_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_capability_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_dataset_binding_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_dataset_binding_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_identity_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "runtime_identity_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "submit_model_update_submission:execute"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_job_dashboard:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_job_dashboard:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_participant_eligibility:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_participant_eligibility:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_round_progress:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_round_progress:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_run_configuration_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "training_run_configuration_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_AGENT", "validate_agent_dataset_access:execute"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "confirm_runtime_infrastructure_prepared:execute"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "register_runtime_infrastructure:execute"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_agent_endpoint_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_agent_endpoint_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_infrastructure_access_view:list"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_infrastructure_access_view:read"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_infrastructure_package_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_infrastructure_package_catalog:read"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_installation_guide:list"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_installation_guide:read"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_installation_plan_catalog:list"),
            SeedGrant("ACTOR_RUNTIME_INSTALLER", "runtime_installation_plan_catalog:read"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "complete_homomorphic_aggregation_session:execute"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "fail_secure_aggregation_session:execute"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "prepare_homomorphic_encryption_context:execute"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "record_encrypted_model_update:execute"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "secure_aggregation_session_catalog:list"),
            SeedGrant("ACTOR_SECURE_AGGREGATION_SERVICE", "secure_aggregation_session_catalog:read"),
            SeedGrant("ACTOR_SECURITY_REVIEWER", "revoke_runtime_identity:execute"),
            SeedGrant("ACTOR_SECURITY_REVIEWER", "runtime_capability_catalog:list"),
            SeedGrant("ACTOR_SECURITY_REVIEWER", "runtime_capability_catalog:read"),
            SeedGrant("ACTOR_SECURITY_REVIEWER", "runtime_identity_catalog:list"),
            SeedGrant("ACTOR_SECURITY_REVIEWER", "runtime_identity_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "issue_service_account_api_token:execute"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "permission_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "permission_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "role_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "role_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "role_permission_grant_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "role_permission_grant_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "service_account_api_token_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "service_account_api_token_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "user_account_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "user_account_catalog:read"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "user_role_assignment_catalog:list"),
            SeedGrant("ACTOR_SUPER_ADMINISTRATOR", "user_role_assignment_catalog:read"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "retry_training_round_participant_selection:execute"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_job_dashboard:list"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_job_dashboard:read"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_participant_eligibility:list"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_participant_eligibility:read"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_round_progress:list"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_round_progress:read"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_run_configuration_catalog:list"),
            SeedGrant("ACTOR_TRAINING_OPERATOR", "training_run_configuration_catalog:read")
        )
    }
}
