package tech.medo.domain.federationmanagement.reactivatefederation

import org.springframework.stereotype.Component
import tech.medo.federationmanagement.reactivatefederation.ReactivateFederationDecision

@Component
class ReactivateFederationDecisionComponent : ReactivateFederationDecision
