package tech.medo.domain.runtimemonitoring.raisetrainingalert

import org.springframework.stereotype.Component
import tech.medo.runtimemonitoring.raisetrainingalert.RaiseTrainingAlertDecision

@Component
class RaiseTrainingAlertDecisionComponent : RaiseTrainingAlertDecision
