create table if not exists app_user (
    id uuid primary key,
    provider_subject varchar(255) unique,
    username varchar(255) not null unique,
    password_hash varchar(255),
    organization_id uuid,
    active boolean not null default true
);

create table if not exists app_role (
    code varchar(100) primary key,
    name varchar(255) not null
);

create table if not exists app_permission (
    code varchar(150) primary key,
    description varchar(255)
);

create table if not exists app_user_role (
    user_id uuid not null references app_user(id),
    role_code varchar(100) not null references app_role(code),
    primary key (user_id, role_code)
);

create table if not exists app_role_permission (
    role_code varchar(100) not null references app_role(code),
    permission_code varchar(150) not null references app_permission(code),
    primary key (role_code, permission_code)
);

insert into app_role(code, name)
values
    ('ADMIN', 'Administrator'),
    ('ACTOR_AGGREGATION_RUNTIME', 'Aggregation Runtime'),
    ('ACTOR_COMPLIANCE_OFFICER', 'Compliance Officer'),
    ('ACTOR_DATA_OWNER', 'Data Owner'),
    ('ACTOR_DATA_STEWARD', 'Data Steward'),
    ('ACTOR_FEDERATION_OWNER', 'Federation Owner'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'Governance Reviewer'),
    ('ACTOR_MLOPS_ENGINEER', 'MLOps Engineer'),
    ('ACTOR_NODE_OPERATOR', 'Node Operator'),
    ('ACTOR_ORGANIZATION_ADMIN', 'Organization Admin'),
    ('ACTOR_PLATFORM_ADMIN', 'Platform Admin'),
    ('ACTOR_PLATFORM_SERVICE', 'Platform Service'),
    ('ACTOR_PLATFORM_USER', 'Platform User'),
    ('ACTOR_RELEASE_MANAGER', 'Release Manager'),
    ('ACTOR_RESEARCH_LEAD', 'Research Lead'),
    ('ACTOR_RUNTIME_AGENT', 'Runtime Agent'),
    ('ACTOR_RUNTIME_INSTALLER', 'Runtime Installer'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'Secure Aggregation Service'),
    ('ACTOR_SECURITY_REVIEWER', 'Security Reviewer'),
    ('ACTOR_TRAINING_OPERATOR', 'Training Operator')
on conflict (code) do nothing;

insert into app_permission(code, description)
values
    ('*:*', 'All permissions'),
    ('acknowledge_training_alert:execute', 'acknowledge_training_alert:execute'),
    ('activate_federation:execute', 'activate_federation:execute'),
    ('activate_organization:execute', 'activate_organization:execute'),
    ('activate_runtime_identity:execute', 'activate_runtime_identity:execute'),
    ('add_dictionary_value:execute', 'add_dictionary_value:execute'),
    ('agent_dataset_access_validation_catalog:list', 'agent_dataset_access_validation_catalog:list'),
    ('agent_dataset_access_validation_catalog:read', 'agent_dataset_access_validation_catalog:read'),
    ('agent_runtime_infrastructure_connection_catalog:list', 'agent_runtime_infrastructure_connection_catalog:list'),
    ('agent_runtime_infrastructure_connection_catalog:read', 'agent_runtime_infrastructure_connection_catalog:read'),
    ('agent_runtime_node_inventory_catalog:list', 'agent_runtime_node_inventory_catalog:list'),
    ('agent_runtime_node_inventory_catalog:read', 'agent_runtime_node_inventory_catalog:read'),
    ('agent_runtime_node_resource_latest:list', 'agent_runtime_node_resource_latest:list'),
    ('agent_runtime_node_resource_latest:read', 'agent_runtime_node_resource_latest:read'),
    ('agent_runtime_telemetry_latest:list', 'agent_runtime_telemetry_latest:list'),
    ('agent_runtime_telemetry_latest:read', 'agent_runtime_telemetry_latest:read'),
    ('approve_dataset_for_training:execute', 'approve_dataset_for_training:execute'),
    ('approve_model:execute', 'approve_model:execute'),
    ('approve_participant:execute', 'approve_participant:execute'),
    ('archive_dictionary:execute', 'archive_dictionary:execute'),
    ('audit_record_log:list', 'audit_record_log:list'),
    ('audit_record_log:read', 'audit_record_log:read'),
    ('cancel_training_job:execute', 'cancel_training_job:execute'),
    ('complete_homomorphic_aggregation_session:execute', 'complete_homomorphic_aggregation_session:execute'),
    ('configure_runtime_dataset_binding:execute', 'configure_runtime_dataset_binding:execute'),
    ('create_federation:execute', 'create_federation:execute'),
    ('create_runtime_installation_plan:execute', 'create_runtime_installation_plan:execute'),
    ('create_training_job:execute', 'create_training_job:execute'),
    ('current_recommended_feature_schema_catalog:list', 'current_recommended_feature_schema_catalog:list'),
    ('current_recommended_feature_schema_catalog:read', 'current_recommended_feature_schema_catalog:read'),
    ('dataset_capability:list', 'dataset_capability:list'),
    ('dataset_capability:read', 'dataset_capability:read'),
    ('dataset_readiness:list', 'dataset_readiness:list'),
    ('dataset_readiness:read', 'dataset_readiness:read'),
    ('deactivate_organization:execute', 'deactivate_organization:execute'),
    ('declare_dataset:execute', 'declare_dataset:execute'),
    ('define_feature_schema:execute', 'define_feature_schema:execute'),
    ('define_training_run_configuration:execute', 'define_training_run_configuration:execute'),
    ('deploy_runtime_agent:execute', 'deploy_runtime_agent:execute'),
    ('deprecate_feature_schema:execute', 'deprecate_feature_schema:execute'),
    ('detect_runtime_capabilities:execute', 'detect_runtime_capabilities:execute'),
    ('dictionary_catalog:list', 'dictionary_catalog:list'),
    ('dictionary_catalog:read', 'dictionary_catalog:read'),
    ('dictionary_value_catalog:list', 'dictionary_value_catalog:list'),
    ('dictionary_value_catalog:read', 'dictionary_value_catalog:read'),
    ('disable_dictionary_value:execute', 'disable_dictionary_value:execute'),
    ('discard_staged_file:execute', 'discard_staged_file:execute'),
    ('enable_dictionary_value:execute', 'enable_dictionary_value:execute'),
    ('fail_secure_aggregation_session:execute', 'fail_secure_aggregation_session:execute'),
    ('fail_training_round:execute', 'fail_training_round:execute'),
    ('feature_schema_catalog:list', 'feature_schema_catalog:list'),
    ('feature_schema_catalog:read', 'feature_schema_catalog:read'),
    ('federation_membership_directory:list', 'federation_membership_directory:list'),
    ('federation_membership_directory:read', 'federation_membership_directory:read'),
    ('federation_overview:list', 'federation_overview:list'),
    ('federation_overview:read', 'federation_overview:read'),
    ('invite_participant:execute', 'invite_participant:execute'),
    ('load_runtime_agent_bootstrap_configuration:execute', 'load_runtime_agent_bootstrap_configuration:execute'),
    ('mark_current_recommended_feature_schema_version:execute', 'mark_current_recommended_feature_schema_version:execute'),
    ('mark_staged_file_consumed:execute', 'mark_staged_file_consumed:execute'),
    ('model_artifact_catalog:list', 'model_artifact_catalog:list'),
    ('model_artifact_catalog:read', 'model_artifact_catalog:read'),
    ('model_catalog:list', 'model_catalog:list'),
    ('model_catalog:read', 'model_catalog:read'),
    ('organization_directory:list', 'organization_directory:list'),
    ('organization_directory:read', 'organization_directory:read'),
    ('pause_training_job:execute', 'pause_training_job:execute'),
    ('plan_runtime_infrastructure:execute', 'plan_runtime_infrastructure:execute'),
    ('prepare_homomorphic_encryption_context:execute', 'prepare_homomorphic_encryption_context:execute'),
    ('profile_agent_dataset:execute', 'profile_agent_dataset:execute'),
    ('promote_model_to_production:execute', 'promote_model_to_production:execute'),
    ('publish_feature_schema:execute', 'publish_feature_schema:execute'),
    ('reactivate_federation:execute', 'reactivate_federation:execute'),
    ('reactivate_organization:execute', 'reactivate_organization:execute'),
    ('record_encrypted_model_update:execute', 'record_encrypted_model_update:execute'),
    ('record_model_evaluation_package:execute', 'record_model_evaluation_package:execute'),
    ('register_dictionary:execute', 'register_dictionary:execute'),
    ('register_model_artifact:execute', 'register_model_artifact:execute'),
    ('register_organization:execute', 'register_organization:execute'),
    ('register_runtime_infrastructure_package:execute', 'register_runtime_infrastructure_package:execute'),
    ('register_runtime_infrastructure:execute', 'register_runtime_infrastructure:execute'),
    ('reject_dataset_for_training:execute', 'reject_dataset_for_training:execute'),
    ('reject_participant:execute', 'reject_participant:execute'),
    ('remove_participant:execute', 'remove_participant:execute'),
    ('report_runtime_agent_started:execute', 'report_runtime_agent_started:execute'),
    ('report_runtime_instance_self_check_passed:execute', 'report_runtime_instance_self_check_passed:execute'),
    ('reprofile_agent_dataset:execute', 'reprofile_agent_dataset:execute'),
    ('resolve_training_alert:execute', 'resolve_training_alert:execute'),
    ('resume_training_job:execute', 'resume_training_job:execute'),
    ('retire_feature_schema:execute', 'retire_feature_schema:execute'),
    ('retire_model:execute', 'retire_model:execute'),
    ('retry_dataset_contract_validation:execute', 'retry_dataset_contract_validation:execute'),
    ('retry_round_execution_after_runtime_failure:execute', 'retry_round_execution_after_runtime_failure:execute'),
    ('retry_round_execution_after_start_failure:execute', 'retry_round_execution_after_start_failure:execute'),
    ('retry_runtime_agent_deployment:execute', 'retry_runtime_agent_deployment:execute'),
    ('retry_training_round_participant_selection:execute', 'retry_training_round_participant_selection:execute'),
    ('revalidate_agent_dataset_access:execute', 'revalidate_agent_dataset_access:execute'),
    ('revoke_dataset_training_approval:execute', 'revoke_dataset_training_approval:execute'),
    ('revoke_participant_invitation:execute', 'revoke_participant_invitation:execute'),
    ('revoke_runtime_identity:execute', 'revoke_runtime_identity:execute'),
    ('rollback_model:execute', 'rollback_model:execute'),
    ('round_execution_catalog:list', 'round_execution_catalog:list'),
    ('round_execution_catalog:read', 'round_execution_catalog:read'),
    ('runtime_agent_endpoint_catalog:list', 'runtime_agent_endpoint_catalog:list'),
    ('runtime_agent_endpoint_catalog:read', 'runtime_agent_endpoint_catalog:read'),
    ('runtime_agent_lifecycle_catalog:list', 'runtime_agent_lifecycle_catalog:list'),
    ('runtime_agent_lifecycle_catalog:read', 'runtime_agent_lifecycle_catalog:read'),
    ('runtime_capability_catalog:list', 'runtime_capability_catalog:list'),
    ('runtime_capability_catalog:read', 'runtime_capability_catalog:read'),
    ('runtime_dataset_binding_catalog:list', 'runtime_dataset_binding_catalog:list'),
    ('runtime_dataset_binding_catalog:read', 'runtime_dataset_binding_catalog:read'),
    ('runtime_dataset_metadata_catalog:list', 'runtime_dataset_metadata_catalog:list'),
    ('runtime_dataset_metadata_catalog:read', 'runtime_dataset_metadata_catalog:read'),
    ('runtime_health_dashboard:list', 'runtime_health_dashboard:list'),
    ('runtime_health_dashboard:read', 'runtime_health_dashboard:read'),
    ('runtime_identity_catalog:list', 'runtime_identity_catalog:list'),
    ('runtime_identity_catalog:read', 'runtime_identity_catalog:read'),
    ('runtime_infrastructure_access_view:list', 'runtime_infrastructure_access_view:list'),
    ('runtime_infrastructure_access_view:read', 'runtime_infrastructure_access_view:read'),
    ('runtime_infrastructure_package_catalog:list', 'runtime_infrastructure_package_catalog:list'),
    ('runtime_infrastructure_package_catalog:read', 'runtime_infrastructure_package_catalog:read'),
    ('runtime_installation_guide:list', 'runtime_installation_guide:list'),
    ('runtime_installation_guide:read', 'runtime_installation_guide:read'),
    ('runtime_installation_plan_catalog:list', 'runtime_installation_plan_catalog:list'),
    ('runtime_installation_plan_catalog:read', 'runtime_installation_plan_catalog:read'),
    ('runtime_node_inventory_view:list', 'runtime_node_inventory_view:list'),
    ('runtime_node_inventory_view:read', 'runtime_node_inventory_view:read'),
    ('runtime_node_resource_latest:list', 'runtime_node_resource_latest:list'),
    ('runtime_node_resource_latest:read', 'runtime_node_resource_latest:read'),
    ('runtime_telemetry_latest:list', 'runtime_telemetry_latest:list'),
    ('runtime_telemetry_latest:read', 'runtime_telemetry_latest:read'),
    ('secure_aggregation_session_catalog:list', 'secure_aggregation_session_catalog:list'),
    ('secure_aggregation_session_catalog:read', 'secure_aggregation_session_catalog:read'),
    ('stage_file_upload:execute', 'stage_file_upload:execute'),
    ('staged_file_catalog:list', 'staged_file_catalog:list'),
    ('staged_file_catalog:read', 'staged_file_catalog:read'),
    ('submit_model_update_submission:execute', 'submit_model_update_submission:execute'),
    ('submit_training_job:execute', 'submit_training_job:execute'),
    ('supersede_feature_schema_version:execute', 'supersede_feature_schema_version:execute'),
    ('suspend_federation:execute', 'suspend_federation:execute'),
    ('suspend_participant:execute', 'suspend_participant:execute'),
    ('training_alert_catalog:list', 'training_alert_catalog:list'),
    ('training_alert_catalog:read', 'training_alert_catalog:read'),
    ('training_job_dashboard:list', 'training_job_dashboard:list'),
    ('training_job_dashboard:read', 'training_job_dashboard:read'),
    ('training_participant_eligibility:list', 'training_participant_eligibility:list'),
    ('training_participant_eligibility:read', 'training_participant_eligibility:read'),
    ('training_round_progress:list', 'training_round_progress:list'),
    ('training_round_progress:read', 'training_round_progress:read'),
    ('training_run_configuration_catalog:list', 'training_run_configuration_catalog:list'),
    ('training_run_configuration_catalog:read', 'training_run_configuration_catalog:read'),
    ('update_dictionary:execute', 'update_dictionary:execute'),
    ('update_training_run_configuration:execute', 'update_training_run_configuration:execute'),
    ('validate_agent_dataset_access:execute', 'validate_agent_dataset_access:execute'),
    ('verify_runtime_infrastructure:execute', 'verify_runtime_infrastructure:execute')
on conflict (code) do nothing;

insert into app_role_permission(role_code, permission_code)
values ('ADMIN', '*:*')
on conflict (role_code, permission_code) do nothing;


insert into app_role_permission(role_code, permission_code)
values
    ('ACTOR_AGGREGATION_RUNTIME', 'fail_training_round:execute'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_job_dashboard:list'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_job_dashboard:read'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_participant_eligibility:list'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_participant_eligibility:read'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_round_progress:list'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_round_progress:read'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_run_configuration_catalog:list'),
    ('ACTOR_AGGREGATION_RUNTIME', 'training_run_configuration_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_dataset_access_validation_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_dataset_access_validation_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_infrastructure_connection_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_infrastructure_connection_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_node_inventory_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_node_inventory_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_node_resource_latest:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_node_resource_latest:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_telemetry_latest:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'agent_runtime_telemetry_latest:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'approve_dataset_for_training:execute'),
    ('ACTOR_COMPLIANCE_OFFICER', 'dataset_capability:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'dataset_capability:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'dataset_readiness:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'dataset_readiness:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'reject_dataset_for_training:execute'),
    ('ACTOR_COMPLIANCE_OFFICER', 'revoke_dataset_training_approval:execute'),
    ('ACTOR_COMPLIANCE_OFFICER', 'round_execution_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'round_execution_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'runtime_agent_lifecycle_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'runtime_agent_lifecycle_catalog:read'),
    ('ACTOR_COMPLIANCE_OFFICER', 'runtime_dataset_binding_catalog:list'),
    ('ACTOR_COMPLIANCE_OFFICER', 'runtime_dataset_binding_catalog:read'),
    ('ACTOR_DATA_OWNER', 'agent_dataset_access_validation_catalog:list'),
    ('ACTOR_DATA_OWNER', 'agent_dataset_access_validation_catalog:read'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_infrastructure_connection_catalog:list'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_infrastructure_connection_catalog:read'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_node_inventory_catalog:list'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_node_inventory_catalog:read'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_node_resource_latest:list'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_node_resource_latest:read'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_telemetry_latest:list'),
    ('ACTOR_DATA_OWNER', 'agent_runtime_telemetry_latest:read'),
    ('ACTOR_DATA_OWNER', 'dataset_capability:list'),
    ('ACTOR_DATA_OWNER', 'dataset_capability:read'),
    ('ACTOR_DATA_OWNER', 'dataset_readiness:list'),
    ('ACTOR_DATA_OWNER', 'dataset_readiness:read'),
    ('ACTOR_DATA_OWNER', 'declare_dataset:execute'),
    ('ACTOR_DATA_OWNER', 'retry_dataset_contract_validation:execute'),
    ('ACTOR_DATA_OWNER', 'round_execution_catalog:list'),
    ('ACTOR_DATA_OWNER', 'round_execution_catalog:read'),
    ('ACTOR_DATA_OWNER', 'runtime_agent_lifecycle_catalog:list'),
    ('ACTOR_DATA_OWNER', 'runtime_agent_lifecycle_catalog:read'),
    ('ACTOR_DATA_OWNER', 'runtime_dataset_binding_catalog:list'),
    ('ACTOR_DATA_OWNER', 'runtime_dataset_binding_catalog:read'),
    ('ACTOR_DATA_STEWARD', 'current_recommended_feature_schema_catalog:list'),
    ('ACTOR_DATA_STEWARD', 'current_recommended_feature_schema_catalog:read'),
    ('ACTOR_DATA_STEWARD', 'define_feature_schema:execute'),
    ('ACTOR_DATA_STEWARD', 'deprecate_feature_schema:execute'),
    ('ACTOR_DATA_STEWARD', 'feature_schema_catalog:list'),
    ('ACTOR_DATA_STEWARD', 'feature_schema_catalog:read'),
    ('ACTOR_DATA_STEWARD', 'mark_current_recommended_feature_schema_version:execute'),
    ('ACTOR_DATA_STEWARD', 'publish_feature_schema:execute'),
    ('ACTOR_DATA_STEWARD', 'retire_feature_schema:execute'),
    ('ACTOR_DATA_STEWARD', 'runtime_dataset_metadata_catalog:list'),
    ('ACTOR_DATA_STEWARD', 'runtime_dataset_metadata_catalog:read'),
    ('ACTOR_DATA_STEWARD', 'supersede_feature_schema_version:execute'),
    ('ACTOR_FEDERATION_OWNER', 'federation_membership_directory:list'),
    ('ACTOR_FEDERATION_OWNER', 'federation_membership_directory:read'),
    ('ACTOR_FEDERATION_OWNER', 'federation_overview:list'),
    ('ACTOR_FEDERATION_OWNER', 'federation_overview:read'),
    ('ACTOR_FEDERATION_OWNER', 'invite_participant:execute'),
    ('ACTOR_FEDERATION_OWNER', 'revoke_participant_invitation:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'approve_model:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'approve_participant:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'federation_membership_directory:list'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'federation_membership_directory:read'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'federation_overview:list'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'federation_overview:read'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'model_catalog:list'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'model_catalog:read'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'record_model_evaluation_package:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'reject_participant:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'remove_participant:execute'),
    ('ACTOR_GOVERNANCE_REVIEWER', 'suspend_participant:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'acknowledge_training_alert:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'audit_record_log:list'),
    ('ACTOR_MLOPS_ENGINEER', 'audit_record_log:read'),
    ('ACTOR_MLOPS_ENGINEER', 'cancel_training_job:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'define_training_run_configuration:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'model_artifact_catalog:list'),
    ('ACTOR_MLOPS_ENGINEER', 'model_artifact_catalog:read'),
    ('ACTOR_MLOPS_ENGINEER', 'pause_training_job:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'register_model_artifact:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'resolve_training_alert:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'resume_training_job:execute'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_health_dashboard:list'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_health_dashboard:read'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_node_inventory_view:list'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_node_inventory_view:read'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_node_resource_latest:list'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_node_resource_latest:read'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_telemetry_latest:list'),
    ('ACTOR_MLOPS_ENGINEER', 'runtime_telemetry_latest:read'),
    ('ACTOR_MLOPS_ENGINEER', 'training_alert_catalog:list'),
    ('ACTOR_MLOPS_ENGINEER', 'training_alert_catalog:read'),
    ('ACTOR_MLOPS_ENGINEER', 'training_job_dashboard:list'),
    ('ACTOR_MLOPS_ENGINEER', 'training_job_dashboard:read'),
    ('ACTOR_MLOPS_ENGINEER', 'training_participant_eligibility:list'),
    ('ACTOR_MLOPS_ENGINEER', 'training_participant_eligibility:read'),
    ('ACTOR_MLOPS_ENGINEER', 'training_round_progress:list'),
    ('ACTOR_MLOPS_ENGINEER', 'training_round_progress:read'),
    ('ACTOR_MLOPS_ENGINEER', 'training_run_configuration_catalog:list'),
    ('ACTOR_MLOPS_ENGINEER', 'training_run_configuration_catalog:read'),
    ('ACTOR_MLOPS_ENGINEER', 'update_training_run_configuration:execute'),
    ('ACTOR_NODE_OPERATOR', 'agent_dataset_access_validation_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'agent_dataset_access_validation_catalog:read'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_infrastructure_connection_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_infrastructure_connection_catalog:read'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_node_inventory_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_node_inventory_catalog:read'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_node_resource_latest:list'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_node_resource_latest:read'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_telemetry_latest:list'),
    ('ACTOR_NODE_OPERATOR', 'agent_runtime_telemetry_latest:read'),
    ('ACTOR_NODE_OPERATOR', 'configure_runtime_dataset_binding:execute'),
    ('ACTOR_NODE_OPERATOR', 'dataset_capability:list'),
    ('ACTOR_NODE_OPERATOR', 'dataset_capability:read'),
    ('ACTOR_NODE_OPERATOR', 'dataset_readiness:list'),
    ('ACTOR_NODE_OPERATOR', 'dataset_readiness:read'),
    ('ACTOR_NODE_OPERATOR', 'reprofile_agent_dataset:execute'),
    ('ACTOR_NODE_OPERATOR', 'retry_round_execution_after_runtime_failure:execute'),
    ('ACTOR_NODE_OPERATOR', 'retry_round_execution_after_start_failure:execute'),
    ('ACTOR_NODE_OPERATOR', 'revalidate_agent_dataset_access:execute'),
    ('ACTOR_NODE_OPERATOR', 'round_execution_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'round_execution_catalog:read'),
    ('ACTOR_NODE_OPERATOR', 'runtime_agent_lifecycle_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'runtime_agent_lifecycle_catalog:read'),
    ('ACTOR_NODE_OPERATOR', 'runtime_dataset_binding_catalog:list'),
    ('ACTOR_NODE_OPERATOR', 'runtime_dataset_binding_catalog:read'),
    ('ACTOR_ORGANIZATION_ADMIN', 'organization_directory:list'),
    ('ACTOR_ORGANIZATION_ADMIN', 'organization_directory:read'),
    ('ACTOR_ORGANIZATION_ADMIN', 'register_organization:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'activate_federation:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'activate_organization:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'activate_runtime_identity:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'add_dictionary_value:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'archive_dictionary:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'create_federation:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'create_runtime_installation_plan:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'deactivate_organization:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'deploy_runtime_agent:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'dictionary_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'dictionary_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'dictionary_value_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'dictionary_value_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'disable_dictionary_value:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'enable_dictionary_value:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'federation_membership_directory:list'),
    ('ACTOR_PLATFORM_ADMIN', 'federation_membership_directory:read'),
    ('ACTOR_PLATFORM_ADMIN', 'federation_overview:list'),
    ('ACTOR_PLATFORM_ADMIN', 'federation_overview:read'),
    ('ACTOR_PLATFORM_ADMIN', 'organization_directory:list'),
    ('ACTOR_PLATFORM_ADMIN', 'organization_directory:read'),
    ('ACTOR_PLATFORM_ADMIN', 'plan_runtime_infrastructure:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'reactivate_federation:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'reactivate_organization:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'register_dictionary:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'register_runtime_infrastructure_package:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'retry_runtime_agent_deployment:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_agent_endpoint_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_agent_endpoint_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_capability_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_capability_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_identity_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_identity_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_infrastructure_access_view:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_infrastructure_access_view:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_infrastructure_package_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_infrastructure_package_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_installation_guide:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_installation_guide:read'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_installation_plan_catalog:list'),
    ('ACTOR_PLATFORM_ADMIN', 'runtime_installation_plan_catalog:read'),
    ('ACTOR_PLATFORM_ADMIN', 'suspend_federation:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'update_dictionary:execute'),
    ('ACTOR_PLATFORM_ADMIN', 'verify_runtime_infrastructure:execute'),
    ('ACTOR_PLATFORM_SERVICE', 'mark_staged_file_consumed:execute'),
    ('ACTOR_PLATFORM_SERVICE', 'staged_file_catalog:list'),
    ('ACTOR_PLATFORM_SERVICE', 'staged_file_catalog:read'),
    ('ACTOR_PLATFORM_USER', 'discard_staged_file:execute'),
    ('ACTOR_PLATFORM_USER', 'stage_file_upload:execute'),
    ('ACTOR_PLATFORM_USER', 'staged_file_catalog:list'),
    ('ACTOR_PLATFORM_USER', 'staged_file_catalog:read'),
    ('ACTOR_RELEASE_MANAGER', 'model_catalog:list'),
    ('ACTOR_RELEASE_MANAGER', 'model_catalog:read'),
    ('ACTOR_RELEASE_MANAGER', 'promote_model_to_production:execute'),
    ('ACTOR_RELEASE_MANAGER', 'retire_model:execute'),
    ('ACTOR_RELEASE_MANAGER', 'rollback_model:execute'),
    ('ACTOR_RESEARCH_LEAD', 'create_training_job:execute'),
    ('ACTOR_RESEARCH_LEAD', 'submit_training_job:execute'),
    ('ACTOR_RESEARCH_LEAD', 'training_job_dashboard:list'),
    ('ACTOR_RESEARCH_LEAD', 'training_job_dashboard:read'),
    ('ACTOR_RESEARCH_LEAD', 'training_participant_eligibility:list'),
    ('ACTOR_RESEARCH_LEAD', 'training_participant_eligibility:read'),
    ('ACTOR_RESEARCH_LEAD', 'training_round_progress:list'),
    ('ACTOR_RESEARCH_LEAD', 'training_round_progress:read'),
    ('ACTOR_RESEARCH_LEAD', 'training_run_configuration_catalog:list'),
    ('ACTOR_RESEARCH_LEAD', 'training_run_configuration_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'agent_dataset_access_validation_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'agent_dataset_access_validation_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_infrastructure_connection_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_infrastructure_connection_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_node_inventory_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_node_inventory_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_node_resource_latest:list'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_node_resource_latest:read'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_telemetry_latest:list'),
    ('ACTOR_RUNTIME_AGENT', 'agent_runtime_telemetry_latest:read'),
    ('ACTOR_RUNTIME_AGENT', 'dataset_capability:list'),
    ('ACTOR_RUNTIME_AGENT', 'dataset_capability:read'),
    ('ACTOR_RUNTIME_AGENT', 'dataset_readiness:list'),
    ('ACTOR_RUNTIME_AGENT', 'dataset_readiness:read'),
    ('ACTOR_RUNTIME_AGENT', 'detect_runtime_capabilities:execute'),
    ('ACTOR_RUNTIME_AGENT', 'load_runtime_agent_bootstrap_configuration:execute'),
    ('ACTOR_RUNTIME_AGENT', 'profile_agent_dataset:execute'),
    ('ACTOR_RUNTIME_AGENT', 'report_runtime_agent_started:execute'),
    ('ACTOR_RUNTIME_AGENT', 'report_runtime_instance_self_check_passed:execute'),
    ('ACTOR_RUNTIME_AGENT', 'round_execution_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'round_execution_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_agent_lifecycle_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_agent_lifecycle_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_capability_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_capability_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_dataset_binding_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_dataset_binding_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_identity_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'runtime_identity_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'submit_model_update_submission:execute'),
    ('ACTOR_RUNTIME_AGENT', 'training_job_dashboard:list'),
    ('ACTOR_RUNTIME_AGENT', 'training_job_dashboard:read'),
    ('ACTOR_RUNTIME_AGENT', 'training_participant_eligibility:list'),
    ('ACTOR_RUNTIME_AGENT', 'training_participant_eligibility:read'),
    ('ACTOR_RUNTIME_AGENT', 'training_round_progress:list'),
    ('ACTOR_RUNTIME_AGENT', 'training_round_progress:read'),
    ('ACTOR_RUNTIME_AGENT', 'training_run_configuration_catalog:list'),
    ('ACTOR_RUNTIME_AGENT', 'training_run_configuration_catalog:read'),
    ('ACTOR_RUNTIME_AGENT', 'validate_agent_dataset_access:execute'),
    ('ACTOR_RUNTIME_INSTALLER', 'register_runtime_infrastructure:execute'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_agent_endpoint_catalog:list'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_agent_endpoint_catalog:read'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_infrastructure_access_view:list'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_infrastructure_access_view:read'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_infrastructure_package_catalog:list'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_infrastructure_package_catalog:read'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_installation_guide:list'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_installation_guide:read'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_installation_plan_catalog:list'),
    ('ACTOR_RUNTIME_INSTALLER', 'runtime_installation_plan_catalog:read'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'complete_homomorphic_aggregation_session:execute'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'fail_secure_aggregation_session:execute'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'prepare_homomorphic_encryption_context:execute'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'record_encrypted_model_update:execute'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'secure_aggregation_session_catalog:list'),
    ('ACTOR_SECURE_AGGREGATION_SERVICE', 'secure_aggregation_session_catalog:read'),
    ('ACTOR_SECURITY_REVIEWER', 'revoke_runtime_identity:execute'),
    ('ACTOR_SECURITY_REVIEWER', 'runtime_capability_catalog:list'),
    ('ACTOR_SECURITY_REVIEWER', 'runtime_capability_catalog:read'),
    ('ACTOR_SECURITY_REVIEWER', 'runtime_identity_catalog:list'),
    ('ACTOR_SECURITY_REVIEWER', 'runtime_identity_catalog:read'),
    ('ACTOR_TRAINING_OPERATOR', 'retry_training_round_participant_selection:execute'),
    ('ACTOR_TRAINING_OPERATOR', 'training_job_dashboard:list'),
    ('ACTOR_TRAINING_OPERATOR', 'training_job_dashboard:read'),
    ('ACTOR_TRAINING_OPERATOR', 'training_participant_eligibility:list'),
    ('ACTOR_TRAINING_OPERATOR', 'training_participant_eligibility:read'),
    ('ACTOR_TRAINING_OPERATOR', 'training_round_progress:list'),
    ('ACTOR_TRAINING_OPERATOR', 'training_round_progress:read'),
    ('ACTOR_TRAINING_OPERATOR', 'training_run_configuration_catalog:list'),
    ('ACTOR_TRAINING_OPERATOR', 'training_run_configuration_catalog:read')
on conflict (role_code, permission_code) do nothing;


insert into app_user(id, provider_subject, username, password_hash, organization_id, active)
values (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000001',
    'admin',
    '{noop}admin',
    null,
    true
)
on conflict (id) do nothing;

insert into app_user_role(user_id, role_code)
values ('00000000-0000-0000-0000-000000000001', 'ADMIN')
on conflict (user_id, role_code) do nothing;
