package tech.medo.identityaccessmanagement.infrastructure.secondary.persistence.serviceaccountapitokencatalogreadmodel

import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.JpaSpecificationExecutor
import java.util.UUID;


interface SpringDataServiceAccountApiTokenCatalogReadModelRepository : JpaRepository<ServiceAccountApiTokenCatalogReadModelEntity, UUID>, JpaSpecificationExecutor<ServiceAccountApiTokenCatalogReadModelEntity> {

}
