package tech.medo.domain.trainingorchestration.locktrainingrunconfiguration

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.locktrainingrunconfiguration.LockTrainingRunConfigurationDecision

@Component
class LockTrainingRunConfigurationDecisionComponent : LockTrainingRunConfigurationDecision
