package tech.medo.domain.trainingorchestration.completetraininground

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.completetraininground.CompleteTrainingRoundDecision

@Component
class CompleteTrainingRoundDecisionComponent : CompleteTrainingRoundDecision
