package tech.medo.domain.federationmanagement.inviteparticipant

import org.springframework.stereotype.Component
import tech.medo.federationmanagement.inviteparticipant.InviteParticipantDecision

@Component
class InviteParticipantDecisionComponent : InviteParticipantDecision
