package tech.medo.runtimeagentoperations.infrastructure.secondary.persistence.agentruntimeinfrastructureconnectioncatalogreadmodel

import org.springframework.data.jpa.repository.JpaRepository
import java.util.UUID;


interface SpringDataAgentRuntimeInfrastructureConnectionCatalogReadModelRepository : JpaRepository<AgentRuntimeInfrastructureConnectionCatalogReadModelEntity, UUID> {

}
