package tech.medo.domain.runtimeagentoperations.validatedatasetcontract

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.validatedatasetcontract.ValidateDatasetContractDecision

@Component
class ValidateDatasetContractDecisionComponent : ValidateDatasetContractDecision
