package tech.medo.domain.secureaggregation.failsecureaggregationsession

import org.springframework.stereotype.Component
import tech.medo.secureaggregation.failsecureaggregationsession.FailSecureAggregationSessionDecision

@Component
class FailSecureAggregationSessionDecisionComponent : FailSecureAggregationSessionDecision
