package tech.medo.domain.runtimemonitoring.recordruntimenoderesourcetelemetry

import org.springframework.stereotype.Component
import tech.medo.runtimemonitoring.recordruntimenoderesourcetelemetry.RecordRuntimeNodeResourceTelemetryDecision

@Component
class RecordRuntimeNodeResourceTelemetryDecisionComponent : RecordRuntimeNodeResourceTelemetryDecision
