package tech.medo.domain.runtimeagentoperations.releaseruntimeenginejobaftercompletion

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.releaseruntimeenginejobaftercompletion.ReleaseRuntimeEngineJobAfterCompletionDecision

@Component
class ReleaseRuntimeEngineJobAfterCompletionDecisionComponent : ReleaseRuntimeEngineJobAfterCompletionDecision
