platform:
  runtime:
    docker-compose:
      enabled: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_ENABLED:true}
      compose-file: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_FILE:../docker-compose-runtime-agent.yml}
      project-name: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_PROJECT_NAME:}
      project-directory: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_PROJECT_DIRECTORY:..}
      agent-service-name: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_AGENT_SERVICE_NAME:federation-learning-runtime-agent}
      agent-version: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_AGENT_VERSION:docker-compose}
      command-timeout: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_COMMAND_TIMEOUT:PT60S}
      supported-deployment-target-types: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_SUPPORTED_DEPLOYMENT_TARGET_TYPES:DOCKER_COMPOSE_HOST}
      supported-environment-types: ${PLATFORM_RUNTIME_DOCKER_COMPOSE_SUPPORTED_ENVIRONMENT_TYPES:DOCKER_COMPOSE}
    k3s:
      enabled: ${PLATFORM_RUNTIME_K3S_ENABLED:true}
      kubectl-executable: ${PLATFORM_RUNTIME_K3S_KUBECTL_EXECUTABLE:kubectl}
      kubeconfig: ${PLATFORM_RUNTIME_K3S_KUBECONFIG:}
      namespace: ${PLATFORM_RUNTIME_K3S_NAMESPACE:default}
      agent-manifest-file: ${PLATFORM_RUNTIME_K3S_AGENT_MANIFEST_FILE:../k3s/runtime-agent.yaml}
      agent-deployment-name: ${PLATFORM_RUNTIME_K3S_AGENT_DEPLOYMENT_NAME:federation-learning-runtime-agent}
      agent-version: ${PLATFORM_RUNTIME_K3S_AGENT_VERSION:k3s}
      command-timeout: ${PLATFORM_RUNTIME_K3S_COMMAND_TIMEOUT:PT60S}
      supported-deployment-target-types: ${PLATFORM_RUNTIME_K3S_SUPPORTED_DEPLOYMENT_TARGET_TYPES:K3S,K3S_CLUSTER}
      supported-environment-types: ${PLATFORM_RUNTIME_K3S_SUPPORTED_ENVIRONMENT_TYPES:K3S,KUBERNETES}