package tech.medo.domain.trainingorchestration.completesecureaggregation

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.completesecureaggregation.CompleteSecureAggregationDecision

@Component
class CompleteSecureAggregationDecisionComponent : CompleteSecureAggregationDecision
