package tech.medo.domain.runtimegovernance.revokeruntimeidentity

import org.springframework.stereotype.Component
import tech.medo.runtimegovernance.revokeruntimeidentity.RevokeRuntimeIdentityDecision

@Component
class RevokeRuntimeIdentityDecisionComponent : RevokeRuntimeIdentityDecision
