package tech.medo.domain.modellifecycle.rollbackmodelversion

import org.springframework.stereotype.Component
import tech.medo.modellifecycle.rollbackmodelversion.RollbackModelVersionDecision

@Component
class RollbackModelVersionDecisionComponent : RollbackModelVersionDecision
