package tech.medo.runtimeagentoperations.acceptexecutionplan

import tech.medo.runtimeagentoperations.acceptexecutionplan.AcceptExecutionPlanCommand

import tech.medo.runtimeagentoperations.acceptexecutionplan.AcceptExecutionPlanResult
import tech.medo.runtimeagentoperations.events.ExecutionPlanAcceptedEvent
import tech.medo.runtimeagentoperations.events.ExecutionPlanRejectedEvent
import tech.medo.runtimeagentoperations.roundexecution.RoundExecutionState


import tech.medo.runtimeagentoperations.domain.states.RoundExecutionStateEnum


interface AcceptExecutionPlanDecision {
    fun decide(command: AcceptExecutionPlanCommand, state: RoundExecutionState, portResult: AcceptExecutionPlanResult, now: java.time.LocalDateTime): List<Any> {
        require(state.currentState == RoundExecutionStateEnum.PLAN_RECEIVED) {
            "AcceptExecutionPlan requires RoundExecution to be PlanReceived."
        }
        return when (portResult) {
                    is AcceptExecutionPlanResult.Succeeded -> listOf(ExecutionPlanAcceptedEvent(executionPlanId = command.executionPlanId, roundExecutionId = command.roundExecutionId, executionSessionId = command.executionSessionId, trainingJobId = command.trainingJobId, trainingRunConfigurationId = command.trainingRunConfigurationId, featureSchemaId = command.featureSchemaId, roundId = command.roundId, roundNumber = command.roundNumber, runtimeId = command.runtimeId, organizationId = command.organizationId, baseModelId = command.baseModelId, baseModelArtifactUri = command.baseModelArtifactUri, baseModelRegistryRef = command.baseModelRegistryRef, baseModelFormat = command.baseModelFormat, baseModelArtifactDigest = command.baseModelArtifactDigest, baseModelSignatureUri = command.baseModelSignatureUri, secureAggregationRequired = command.secureAggregationRequired, secureAggregationSessionId = command.secureAggregationSessionId, encryptionScheme = command.encryptionScheme, publicKeyVersion = command.publicKeyVersion, publicKeyRef = command.publicKeyRef, encryptedParameterScale = command.encryptedParameterScale, localExecutionRequirementsSatisfied = portResult.localExecutionRequirementsSatisfied, runtimeIdentityMatched = portResult.runtimeIdentityMatched, runtimeDatasetBindingAvailable = portResult.runtimeDatasetBindingAvailable, datasetAccessValidated = portResult.datasetAccessValidated, baseModelAvailable = portResult.baseModelAvailable, trainingConfigurationSupported = portResult.trainingConfigurationSupported, runtimeResourceAvailable = portResult.runtimeResourceAvailable, runtimeAgentIdle = portResult.runtimeAgentIdle))
                    is AcceptExecutionPlanResult.Rejected -> listOf(ExecutionPlanRejectedEvent(executionPlanId = command.executionPlanId, roundExecutionId = command.roundExecutionId, executionSessionId = command.executionSessionId, trainingJobId = command.trainingJobId, trainingRunConfigurationId = command.trainingRunConfigurationId, featureSchemaId = command.featureSchemaId, roundId = command.roundId, roundNumber = command.roundNumber, runtimeId = command.runtimeId, organizationId = command.organizationId, baseModelId = command.baseModelId, baseModelArtifactUri = command.baseModelArtifactUri, baseModelRegistryRef = command.baseModelRegistryRef, baseModelFormat = command.baseModelFormat, baseModelArtifactDigest = command.baseModelArtifactDigest, baseModelSignatureUri = command.baseModelSignatureUri, secureAggregationRequired = command.secureAggregationRequired, secureAggregationSessionId = command.secureAggregationSessionId, encryptionScheme = command.encryptionScheme, publicKeyVersion = command.publicKeyVersion, publicKeyRef = command.publicKeyRef, encryptedParameterScale = command.encryptedParameterScale, localExecutionRequirementsSatisfied = portResult.localExecutionRequirementsSatisfied, runtimeIdentityMatched = portResult.runtimeIdentityMatched, runtimeDatasetBindingAvailable = portResult.runtimeDatasetBindingAvailable, datasetAccessValidated = portResult.datasetAccessValidated, baseModelAvailable = portResult.baseModelAvailable, trainingConfigurationSupported = portResult.trainingConfigurationSupported, runtimeResourceAvailable = portResult.runtimeResourceAvailable, runtimeAgentIdle = portResult.runtimeAgentIdle, rejectionReasons = portResult.rejectionReasons))
                    is AcceptExecutionPlanResult.Unavailable -> listOf(ExecutionPlanRejectedEvent(executionPlanId = command.executionPlanId, roundExecutionId = command.roundExecutionId, executionSessionId = command.executionSessionId, trainingJobId = command.trainingJobId, trainingRunConfigurationId = command.trainingRunConfigurationId, featureSchemaId = command.featureSchemaId, roundId = command.roundId, roundNumber = command.roundNumber, runtimeId = command.runtimeId, organizationId = command.organizationId, baseModelId = command.baseModelId, baseModelArtifactUri = command.baseModelArtifactUri, baseModelRegistryRef = command.baseModelRegistryRef, baseModelFormat = command.baseModelFormat, baseModelArtifactDigest = command.baseModelArtifactDigest, baseModelSignatureUri = command.baseModelSignatureUri, secureAggregationRequired = command.secureAggregationRequired, secureAggregationSessionId = command.secureAggregationSessionId, encryptionScheme = command.encryptionScheme, publicKeyVersion = command.publicKeyVersion, publicKeyRef = command.publicKeyRef, encryptedParameterScale = command.encryptedParameterScale, localExecutionRequirementsSatisfied = false /* TODO: provide localExecutionRequirementsSatisfied */, runtimeIdentityMatched = false /* TODO: provide runtimeIdentityMatched */, runtimeDatasetBindingAvailable = false /* TODO: provide runtimeDatasetBindingAvailable */, datasetAccessValidated = false /* TODO: provide datasetAccessValidated */, baseModelAvailable = false /* TODO: provide baseModelAvailable */, trainingConfigurationSupported = false /* TODO: provide trainingConfigurationSupported */, runtimeResourceAvailable = false /* TODO: provide runtimeResourceAvailable */, runtimeAgentIdle = false /* TODO: provide runtimeAgentIdle */, rejectionReasons = emptyList() /* TODO: provide rejectionReasons */))
                }
    }
}
