package tech.medo.domain.runtimemonitoring.acknowledgetrainingalert

import org.springframework.stereotype.Component
import tech.medo.runtimemonitoring.acknowledgetrainingalert.AcknowledgeTrainingAlertDecision

@Component
class AcknowledgeTrainingAlertDecisionComponent : AcknowledgeTrainingAlertDecision
