// Generated from config.json by the refine generator.
import { IResourceItem } from "@refinedev/core";
import { FlaskConical, LayoutDashboard, Package } from "lucide-react";
import { resolveMenuIcon } from "@/domain/menu-icons";
import { getAppConfig } from "@/providers/app-config";

export const backendModules = [
  {
    name: "federation-learning-support",
    label: "Federation Learning Support",
    dataProviderName: "federation-learning-support",
    apiUrl: getAppConfig("VITE_FEDERATION_LEARNING_SUPPORT_API_URL", "http://localhost:8080"),
    homeRoute: "/dashboard",
    resources: [],
  },
  {
    name: "federation-learning-platform",
    label: "Federation Learning Platform",
    dataProviderName: "federation-learning-platform",
    apiUrl: getAppConfig("VITE_FEDERATION_LEARNING_PLATFORM_API_URL", "http://localhost:8081"),
    homeRoute: "/dashboard",
    resources: [],
  },
  {
    name: "federation-learning-runtime-agent",
    label: "Federation Learning Runtime Agent",
    dataProviderName: "federation-learning-runtime-agent",
    apiUrl: getAppConfig("VITE_FEDERATION_LEARNING_RUNTIME_AGENT_API_URL", "http://localhost:8082"),
    homeRoute: "/agent-dataset-access-validation-catalog",
    resources: ["agent-dataset-access-validation-catalog","agent-dictionary-value-catalog","agent-feature-schema-catalog","agent-organization-directory","agent-runtime-identity-catalog","agent-runtime-infrastructure-connection-catalog","agent-runtime-node-inventory-catalog","agent-runtime-node-resource-latest","agent-runtime-telemetry-latest","dataset-capability","dataset-readiness","permission-catalog","role-catalog","role-permission-grant-catalog","round-execution-catalog","runtime-agent-lifecycle-catalog","runtime-dataset-binding-catalog","service-account-api-token-catalog","user-account-catalog","user-role-assignment-catalog"],
  },
];

export const authBackendModule =
  backendModules.find((module) => module.name === "federation-learning-runtime-agent")
  ?? backendModules[0];

export const fileUploadCapability = null;

export const resources: IResourceItem[] = [
  {
    name: "dashboard",
    list: "/dashboard",
    meta: {
      label: "Dashboard",
      i18nKey: "resources.dashboard.label",
      icon: resolveMenuIcon({ type: "dashboard", name: "dashboard", fallback: <LayoutDashboard /> }),
    },
  },
  {
    name: "identityaccessmanagement",
    meta: {
      label: "Identity Access Management",
      i18nKey: "chapters.identityaccessmanagement.label",
      icon: resolveMenuIcon({ type: "chapter", name: "identityaccessmanagement", label: "Identity Access Management", fallback: <FlaskConical /> }),
    },
  },
  {
    name: "runtimeagentoperations",
    meta: {
      label: "Runtime Agent Operations",
      i18nKey: "chapters.runtimeagentoperations.label",
      icon: resolveMenuIcon({ type: "chapter", name: "runtimeagentoperations", label: "Runtime Agent Operations", fallback: <FlaskConical /> }),
    },
  },
  {
    name: "agent_dataset_access_validation_catalog",
    list: "/agent-dataset-access-validation-catalog",
    show: "/agent-dataset-access-validation-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Dataset Access Validation Catalog",
      i18nKey: "resources.agent_dataset_access_validation_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_dataset_access_validation_catalog", label: "Agent Dataset Access Validation Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_dataset_access_validation_catalog_read_model_entity",
      idField: "datasetAccessValidationId",
      idFields: ["datasetAccessValidationId"],
      queryFields: ["datasetAccessValidationId","runtimeDatasetBindingId","datasetId","organizationId","organizationName","featureSchemaId","featureDomain","featureSchemaVersion","runtimeId","datasetName","runtimeName","readable","schemaReadable","sampleBatchReadable","validationStatus","failureReason","validatedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentdatasetaccessvalidation",
      queryRoute: "agentdatasetaccessvalidationcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_dictionary_value_catalog",
    list: "/agent-dictionary-value-catalog",
    show: "/agent-dictionary-value-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Dictionary Value Catalog",
      i18nKey: "resources.agent_dictionary_value_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_dictionary_value_catalog", label: "Agent Dictionary Value Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_dictionary_value_catalog_read_model_entity",
      idField: "dictionaryValueId",
      idFields: ["dictionaryValueId"],
      queryFields: ["dictionaryValueId","dictionaryId","dictionaryCode","valueCode","displayName","displayOrder","active","state","syncedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentdictionaryvaluecatalog",
      queryRoute: "agentdictionaryvaluecatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_feature_schema_catalog",
    list: "/agent-feature-schema-catalog",
    show: "/agent-feature-schema-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Feature Schema Catalog",
      i18nKey: "resources.agent_feature_schema_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_feature_schema_catalog", label: "Agent Feature Schema Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_feature_schema_catalog_read_model_entity",
      idField: "featureSchemaId",
      idFields: ["featureSchemaId"],
      queryFields: ["featureSchemaId","featureDomain","featureSchemaVersion","schemaStatus","syncedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentfeatureschemacatalog",
      queryRoute: "agentfeatureschemacatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_organization_directory",
    list: "/agent-organization-directory",
    show: "/agent-organization-directory/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Organization Directory",
      i18nKey: "resources.agent_organization_directory.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_organization_directory", label: "Agent Organization Directory", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_organization_directory_read_model_entity",
      idField: "organizationId",
      idFields: ["organizationId"],
      queryFields: ["organizationId","organizationName","organizationType","state","syncedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentorganizationdirectory",
      queryRoute: "agentorganizationdirectory",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_identity_catalog",
    list: "/agent-runtime-identity-catalog",
    show: "/agent-runtime-identity-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Identity Catalog",
      i18nKey: "resources.agent_runtime_identity_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_runtime_identity_catalog", label: "Agent Runtime Identity Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_runtime_identity_catalog_read_model_entity",
      idField: "runtimeId",
      idFields: ["runtimeId"],
      queryFields: ["runtimeId","runtimeInfrastructureId","runtimeAgentId","organizationId","organizationName","runtimeName","identityStatus","activatedAt","revokedAt","syncedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimeidentitycatalog",
      queryRoute: "agentruntimeidentitycatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_infrastructure_connection_catalog",
    list: "/agent-runtime-infrastructure-connection-catalog",
    show: "/agent-runtime-infrastructure-connection-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Infrastructure Connection Catalog",
      i18nKey: "resources.agent_runtime_infrastructure_connection_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_runtime_infrastructure_connection_catalog", label: "Agent Runtime Infrastructure Connection Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_runtime_infrastructure_connection_catalog_read_model_entity",
      idField: "runtimeInfrastructureId",
      idFields: ["runtimeInfrastructureId"],
      queryFields: ["runtimeInfrastructureId","runtimeAgentId","runtimePlatformConnectionReady","platformApiReachable","agentAuthenticationSucceeded","controlChannelEstablished","heartbeatAccepted","connectedAt","connectionReportFailedAt","connectionReportFailureReason","connectionReportRetryable"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimeinfrastructureconnection",
      queryRoute: "agentruntimeinfrastructureconnectioncatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_node_inventory_catalog",
    list: "/agent-runtime-node-inventory-catalog",
    show: "/agent-runtime-node-inventory-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Node Inventory Catalog",
      i18nKey: "resources.agent_runtime_node_inventory_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_runtime_node_inventory_catalog", label: "Agent Runtime Node Inventory Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_runtime_node_inventory_catalog_read_model_entity",
      idField: "runtimeNodeInventoryReportId",
      idFields: ["runtimeNodeInventoryReportId"],
      queryFields: ["runtimeNodeInventoryReportId","organizationId","runtimeInfrastructureId","runtimeAgentId","organizationName","runtimeNodeName","infrastructureNodeId","runtimeNodeRole","nodeReady","runtimeEngineVersion","containerEngineVersion","operatingSystem","architecture","inventoryHash","discoveredAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimenodeinventory",
      queryRoute: "agentruntimenodeinventorycatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_node_resource_latest",
    list: "/agent-runtime-node-resource-latest",
    show: "/agent-runtime-node-resource-latest/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Node Resource Latest",
      i18nKey: "resources.agent_runtime_node_resource_latest.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_runtime_node_resource_latest", label: "Agent Runtime Node Resource Latest", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_runtime_node_resource_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      queryFields: ["nodeId","runtimeAgentId","runtimeInfrastructureId","runtimeNodeName","nodeReady","allocatableCpuCores","allocatableMemoryGb","allocatableGpuCount","allocatedCpuCores","allocatedMemoryGb","allocatedGpuCount","availableCpuCores","availableMemoryGb","availableGpuCount","runningWorkloadCount","workloadCapacity","observedAt","telemetryRetentionPolicy"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimenoderesourcetelemetry",
      queryRoute: "agentruntimenoderesourcelatest",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "agent_runtime_telemetry_latest",
    list: "/agent-runtime-telemetry-latest",
    show: "/agent-runtime-telemetry-latest/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Agent Runtime Telemetry Latest",
      i18nKey: "resources.agent_runtime_telemetry_latest.label",
      icon: resolveMenuIcon({ type: "resource", name: "agent_runtime_telemetry_latest", label: "Agent Runtime Telemetry Latest", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "agent_runtime_telemetry_latest_read_model_entity",
      idField: "nodeId",
      idFields: ["nodeId"],
      queryFields: ["nodeId","runtimeAgentId","federationId","trainingJobId","roundExecutionId","cpuLoad","gpuLoad","memoryLoad","lastHeartbeatAt","telemetryRetentionPolicy"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "agentruntimetelemetry",
      queryRoute: "agentruntimetelemetrylatest",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "dataset_capability",
    list: "/dataset-capability",
    create: "/dataset-capability/command/declare-dataset",
    show: "/dataset-capability/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Dataset Capability",
      i18nKey: "resources.dataset_capability.label",
      icon: resolveMenuIcon({ type: "resource", name: "dataset_capability", label: "Dataset Capability", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "dataset_capability_read_model_entity",
      idField: "datasetId",
      idFields: ["datasetId"],
      queryFields: ["datasetId","organizationId","runtimeId","featureSchemaId","organizationName","featureDomain","featureSchemaVersion","datasetName","datasetUsage","sampleCount","featureCount","schemaCompatible","labelCompatible","qualityScore","nonIidScore","metadataReportId","metadataStatus","contractStatus","approvalStatus","approved","lastProfiledAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "dataset",
      queryRoute: "datasetcapability",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/dataset-capability/:id/command/:command",
      commands: {
        declareDataset: { label: "Declare Dataset", i18nKey: "resources.dataset_capability.commands.declareDataset.label", route: "/dataset-capability/command/declare-dataset", dataProviderName: "federation-learning-runtime-agent" },
        retryDatasetContractValidation: { label: "Retry Dataset Contract Validation", i18nKey: "resources.dataset_capability.commands.retryDatasetContractValidation.label", route: "/dataset-capability/:id/command/retry-dataset-contract-validation", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        rejectDatasetForTraining: { label: "Reject Dataset For Training", i18nKey: "resources.dataset_capability.commands.rejectDatasetForTraining.label", route: "/dataset-capability/:id/command/reject-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        approveDatasetForTraining: { label: "Approve Dataset For Training", i18nKey: "resources.dataset_capability.commands.approveDatasetForTraining.label", route: "/dataset-capability/:id/command/approve-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        revokeDatasetTrainingApproval: { label: "Revoke Dataset Training Approval", i18nKey: "resources.dataset_capability.commands.revokeDatasetTrainingApproval.label", route: "/dataset-capability/:id/command/revoke-dataset-training-approval", dataProviderName: "federation-learning-runtime-agent", stateField: "approvalStatus", allowedStates: ["Approved"] },
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.dataset_capability.commands.configureRuntimeDatasetBinding.label", route: "/dataset-capability/:id/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "dataset_readiness",
    list: "/dataset-readiness",
    show: "/dataset-readiness/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Dataset Readiness",
      i18nKey: "resources.dataset_readiness.label",
      icon: resolveMenuIcon({ type: "resource", name: "dataset_readiness", label: "Dataset Readiness", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "dataset_readiness_read_model_entity",
      idField: "datasetId",
      idFields: ["datasetId"],
      queryFields: ["datasetId","organizationId","runtimeId","featureSchemaId","datasetName","organizationName","featureDomain","featureSchemaVersion","datasetUsage","metadataStatus","contractStatus","approvalStatus","accessStatus","runtimeStatus","overallReadiness","readyForTraining","canBeSelectedForTraining","readinessScore","sampleCount","featureCount","schemaCompatible","labelCompatible","qualityScore","nonIidScore","classBalanceScore","metadataReportId","datasetAccessValidationId","readable","schemaReadable","sampleBatchReadable","lastProfiledAt","lastAccessValidatedAt","lastRuntimeHeartbeatAt","lastUpdatedAt"],
      actionControls: {"enabledFields":["canBeSelectedForTraining"]},
      aggregateRoute: "dataset",
      queryRoute: "datasetreadiness",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/dataset-readiness/:id/command/:command",
      commands: {
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.dataset_readiness.commands.configureRuntimeDatasetBinding.label", route: "/dataset-readiness/:id/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
        rejectDatasetForTraining: { label: "Reject Dataset For Training", i18nKey: "resources.dataset_readiness.commands.rejectDatasetForTraining.label", route: "/dataset-readiness/:id/command/reject-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        approveDatasetForTraining: { label: "Approve Dataset For Training", i18nKey: "resources.dataset_readiness.commands.approveDatasetForTraining.label", route: "/dataset-readiness/:id/command/approve-dataset-for-training", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        retryDatasetContractValidation: { label: "Retry Dataset Contract Validation", i18nKey: "resources.dataset_readiness.commands.retryDatasetContractValidation.label", route: "/dataset-readiness/:id/command/retry-dataset-contract-validation", dataProviderName: "federation-learning-runtime-agent", stateField: "contractStatus", allowedStates: ["ContractValidationCompleted"] },
        revokeDatasetTrainingApproval: { label: "Revoke Dataset Training Approval", i18nKey: "resources.dataset_readiness.commands.revokeDatasetTrainingApproval.label", route: "/dataset-readiness/:id/command/revoke-dataset-training-approval", dataProviderName: "federation-learning-runtime-agent", stateField: "approvalStatus", allowedStates: ["Approved"] },
      },
      canDelete: false,
    },
  },
  {
    name: "permission_catalog",
    list: "/permission-catalog",
    create: "/permission-catalog/command/register-permission",
    show: "/permission-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "Permission Catalog",
      i18nKey: "resources.permission_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "permission_catalog", label: "Permission Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "permission_catalog_read_model_entity",
      idField: "permissionId",
      idFields: ["permissionId"],
      queryFields: ["permissionId","permissionCode","permissionName","description"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "permission",
      queryRoute: "permissioncatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/permission-catalog/:id/command/:command",
      commands: {
        registerPermission: { label: "Register Permission", i18nKey: "resources.permission_catalog.commands.registerPermission.label", route: "/permission-catalog/command/register-permission", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "role_catalog",
    list: "/role-catalog",
    create: "/role-catalog/command/register-role",
    show: "/role-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "Role Catalog",
      i18nKey: "resources.role_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "role_catalog", label: "Role Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "role_catalog_read_model_entity",
      idField: "roleId",
      idFields: ["roleId"],
      queryFields: ["roleId","roleCode","roleName"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "role",
      queryRoute: "rolecatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/role-catalog/:id/command/:command",
      commands: {
        registerRole: { label: "Register Role", i18nKey: "resources.role_catalog.commands.registerRole.label", route: "/role-catalog/command/register-role", dataProviderName: "federation-learning-runtime-agent" },
        grantPermissionToRole: { label: "Grant Permission To Role", i18nKey: "resources.role_catalog.commands.grantPermissionToRole.label", route: "/role-catalog/:id/command/grant-permission-to-role", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "role_permission_grant_catalog",
    list: "/role-permission-grant-catalog",
    show: "/role-permission-grant-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "Role Permission Grant Catalog",
      i18nKey: "resources.role_permission_grant_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "role_permission_grant_catalog", label: "Role Permission Grant Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "role_permission_grant_catalog_read_model_entity",
      idField: "roleCode",
      idFields: ["roleCode","permissionCode"],
      queryFields: ["roleId","roleCode","roleName","permissionCode","permissionName"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "rolepermissiongrant",
      queryRoute: "rolepermissiongrantcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
  {
    name: "round_execution_catalog",
    list: "/round-execution-catalog",
    show: "/round-execution-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Round Execution Catalog",
      i18nKey: "resources.round_execution_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "round_execution_catalog", label: "Round Execution Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "round_execution_catalog_read_model_entity",
      idField: "roundExecutionId",
      idFields: ["roundExecutionId"],
      queryFields: ["roundExecutionId","executionSessionId","executionPlanId","trainingJobId","trainingRunConfigurationId","roundId","roundNumber","organizationId","runtimeId","state","featureSchemaId","baseModelId","runtimeEngineProfileId","runtimeEngineProfileName","runtimeEnginePluginProfile","runtimeEngineImage","runtimeEngineImageDigest","runtimeEngineJobId","runtimeEngineObservedStatus","runtimeEngineObservationAt","localUpdateArtifactRef","metricsArtifactRef","localExecutionRequirementsSatisfied","runtimeIdentityMatched","runtimeDatasetBindingAvailable","datasetAccessValidated","baseModelAvailable","trainingConfigurationSupported","runtimeResourceAvailable","runtimeAgentIdle","updateArtifactId","artifactRef","artifactDigest","trainingLoss","receivedAt","acceptedAt","rejectedAt","startedAt","completedAt","failedAt","submittedAt","failureReason","retryReason","runtimeEngineReleased","runtimeEngineReleaseFailureReason"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "roundexecution",
      queryRoute: "roundexecutioncatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/round-execution-catalog/:id/command/:command",
      commands: {
        retryRoundExecutionAfterStartFailure: { label: "Retry Round Execution After Start Failure", i18nKey: "resources.round_execution_catalog.commands.retryRoundExecutionAfterStartFailure.label", route: "/round-execution-catalog/:id/command/retry-round-execution-after-start-failure", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["StartFailed"] },
        retryRoundExecutionAfterRuntimeFailure: { label: "Retry Round Execution After Runtime Failure", i18nKey: "resources.round_execution_catalog.commands.retryRoundExecutionAfterRuntimeFailure.label", route: "/round-execution-catalog/:id/command/retry-round-execution-after-runtime-failure", dataProviderName: "federation-learning-runtime-agent", stateField: "state", allowedStates: ["Failed"] },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_agent_lifecycle_catalog",
    list: "/runtime-agent-lifecycle-catalog",
    create: "/runtime-agent-lifecycle-catalog/command/load-runtime-agent-bootstrap-configuration",
    show: "/runtime-agent-lifecycle-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Runtime Agent Lifecycle Catalog",
      i18nKey: "resources.runtime_agent_lifecycle_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "runtime_agent_lifecycle_catalog", label: "Runtime Agent Lifecycle Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "runtime_agent_lifecycle_catalog_read_model_entity",
      idField: "runtimeAgentId",
      idFields: ["runtimeAgentId"],
      queryFields: ["runtimeAgentId","runtimeInfrastructureId","agentVersion","runtimeAgentEndpoint","endpointScope","lifecycleStatus","bootstrapConfigurationLoaded","bootstrapFailureReason","runtimeAgentSelfCheckPassed","configurationLoaded","secretStoreAccessible","runtimeEngineAdapterReady","modelRepositoryClientReady","localDatasetBindingStoreReady","workingDirectoryWritable","bootstrappedAt","bootstrapFailedAt","startedAt","readyAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimeagentlifecycle",
      queryRoute: "runtimeagentlifecyclecatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/runtime-agent-lifecycle-catalog/:id/command/:command",
      commands: {
        loadRuntimeAgentBootstrapConfiguration: { label: "Load Runtime Agent Bootstrap Configuration", i18nKey: "resources.runtime_agent_lifecycle_catalog.commands.loadRuntimeAgentBootstrapConfiguration.label", route: "/runtime-agent-lifecycle-catalog/command/load-runtime-agent-bootstrap-configuration", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "runtime_dataset_binding_catalog",
    list: "/runtime-dataset-binding-catalog",
    create: "/runtime-dataset-binding-catalog/command/configure-runtime-dataset-binding",
    show: "/runtime-dataset-binding-catalog/show/:id",
    meta: {
      parent: "runtimeagentoperations",
      label: "Runtime Dataset Binding Catalog",
      i18nKey: "resources.runtime_dataset_binding_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "runtime_dataset_binding_catalog", label: "Runtime Dataset Binding Catalog", parent: "runtimeagentoperations", fallback: <Package /> }),
      tableName: "runtime_dataset_binding_catalog_read_model_entity",
      idField: "runtimeDatasetBindingId",
      idFields: ["runtimeDatasetBindingId"],
      queryFields: ["runtimeDatasetBindingId","datasetId","organizationId","runtimeId","organizationName","featureSchemaId","featureDomain","featureSchemaVersion","datasetName","runtimeName","filePath","dataFormat","configuredAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "runtimedatasetbinding",
      queryRoute: "runtimedatasetbindingcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/runtime-dataset-binding-catalog/:id/command/:command",
      commands: {
        configureRuntimeDatasetBinding: { label: "Configure Runtime Dataset Binding", i18nKey: "resources.runtime_dataset_binding_catalog.commands.configureRuntimeDatasetBinding.label", route: "/runtime-dataset-binding-catalog/command/configure-runtime-dataset-binding", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "service_account_api_token_catalog",
    list: "/service-account-api-token-catalog",
    create: "/service-account-api-token-catalog/command/issue-service-account-api-token",
    show: "/service-account-api-token-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "Service Account Api Token Catalog",
      i18nKey: "resources.service_account_api_token_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "service_account_api_token_catalog", label: "Service Account Api Token Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "service_account_api_token_catalog_read_model_entity",
      idField: "apiTokenId",
      idFields: ["apiTokenId"],
      queryFields: ["apiTokenId","userAccountId","username","tokenName","tokenPrefix","issuedAt"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "serviceaccountapitoken",
      queryRoute: "serviceaccountapitokencatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/service-account-api-token-catalog/:id/command/:command",
      commands: {
        issueServiceAccountApiToken: { label: "Issue Service Account Api Token", i18nKey: "resources.service_account_api_token_catalog.commands.issueServiceAccountApiToken.label", route: "/service-account-api-token-catalog/command/issue-service-account-api-token", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "user_account_catalog",
    list: "/user-account-catalog",
    create: "/user-account-catalog/command/register-user-account",
    show: "/user-account-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "User Account Catalog",
      i18nKey: "resources.user_account_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "user_account_catalog", label: "User Account Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "user_account_catalog_read_model_entity",
      idField: "userAccountId",
      idFields: ["userAccountId"],
      queryFields: ["userAccountId","username","providerSubject","userSource","passwordHash","active"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "useraccount",
      queryRoute: "useraccountcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      commandRoute: "/user-account-catalog/:id/command/:command",
      commands: {
        registerUserAccount: { label: "Register User Account", i18nKey: "resources.user_account_catalog.commands.registerUserAccount.label", route: "/user-account-catalog/command/register-user-account", dataProviderName: "federation-learning-runtime-agent" },
        generateUserAccountLoginPassword: { label: "Generate User Account Login Password", i18nKey: "resources.user_account_catalog.commands.generateUserAccountLoginPassword.label", route: "/user-account-catalog/:id/command/generate-user-account-login-password", dataProviderName: "federation-learning-runtime-agent" },
        deactivateUserAccount: { label: "Deactivate User Account", i18nKey: "resources.user_account_catalog.commands.deactivateUserAccount.label", route: "/user-account-catalog/:id/command/deactivate-user-account", dataProviderName: "federation-learning-runtime-agent" },
        assignRoleToUser: { label: "Assign Role To User", i18nKey: "resources.user_account_catalog.commands.assignRoleToUser.label", route: "/user-account-catalog/:id/command/assign-role-to-user", dataProviderName: "federation-learning-runtime-agent" },
      },
      canDelete: false,
    },
  },
  {
    name: "user_role_assignment_catalog",
    list: "/user-role-assignment-catalog",
    show: "/user-role-assignment-catalog/show/:id",
    meta: {
      parent: "identityaccessmanagement",
      label: "User Role Assignment Catalog",
      i18nKey: "resources.user_role_assignment_catalog.label",
      icon: resolveMenuIcon({ type: "resource", name: "user_role_assignment_catalog", label: "User Role Assignment Catalog", parent: "identityaccessmanagement", fallback: <Package /> }),
      tableName: "user_role_assignment_catalog_read_model_entity",
      idField: "userAccountId",
      idFields: ["userAccountId","roleCode"],
      queryFields: ["userAccountId","username","roleCode","roleName"],
      actionControls: {"enabledFields":[]},
      aggregateRoute: "userroleassignment",
      queryRoute: "userroleassignmentcatalog",
      dataProviderName: "federation-learning-runtime-agent",
      moduleName: "federation-learning-runtime-agent",
      moduleLabel: "Federation Learning Runtime Agent",
      canDelete: false,
    },
  },
];
