package tech.medo.domain.trainingorchestration.canceltrainingjob

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.canceltrainingjob.CancelTrainingJobDecision

@Component
class CancelTrainingJobDecisionComponent : CancelTrainingJobDecision
