package tech.medo.domain.trainingorchestration.requestsecureaggregation

import org.springframework.stereotype.Component
import tech.medo.trainingorchestration.requestsecureaggregation.RequestSecureAggregationDecision

@Component
class RequestSecureAggregationDecisionComponent : RequestSecureAggregationDecision
