package tech.medo.domain.modellifecycle.retiremodelversion

import org.springframework.stereotype.Component
import tech.medo.modellifecycle.retiremodelversion.RetireModelVersionDecision

@Component
class RetireModelVersionDecisionComponent : RetireModelVersionDecision
