-- Generated by the Medol operations generator.
-- This file runs during the first PostgreSQL container initialization.
SELECT 'CREATE DATABASE "federation_learning_platform";' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'federation_learning_platform')\gexec
SELECT 'CREATE DATABASE "federation_learning_runtime_agent";' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'federation_learning_runtime_agent')\gexec
SELECT 'CREATE DATABASE "federation_learning_support";' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'federation_learning_support')\gexec
