package tech.medo.domain.runtimeagentoperations.failroundexecution

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.failroundexecution.FailRoundExecutionDecision

@Component
class FailRoundExecutionDecisionComponent : FailRoundExecutionDecision
