package tech.medo.domain.runtimeagentoperations.releaseruntimeenginejobafterruntimeretryfailure

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.releaseruntimeenginejobafterruntimeretryfailure.ReleaseRuntimeEngineJobAfterRuntimeRetryFailureDecision

@Component
class ReleaseRuntimeEngineJobAfterRuntimeRetryFailureDecisionComponent : ReleaseRuntimeEngineJobAfterRuntimeRetryFailureDecision
