package tech.medo.domain.runtimeagentoperations.configureruntimedatasetbinding

import org.springframework.stereotype.Component
import tech.medo.runtimeagentoperations.configureruntimedatasetbinding.ConfigureRuntimeDatasetBindingDecision

@Component
class ConfigureRuntimeDatasetBindingDecisionComponent : ConfigureRuntimeDatasetBindingDecision
